@set PROCISE_DIR=C:/Program Files/Fudan Micro/Procise
@set TCL_LIBRARY=%PROCISE_DIR%/tcl8.4
@set PATH=%PROCISE_DIR%/dll;%PROCISE_DIR%/bin;%PATH%
@set ICTIME_HOME=%PROCISE_DIR%
@set APP_DIR=%PROCISE_DIR%
@set FMSH_DB=%PROCISE_DIR%/db
@procise.exe D:/SRIO_ZL/EB4110/03_FPGA/LTEB41_1010/FPGA/EB4110_pack/EB4110_FPGA_20260410_2/10_PRJ/procise_run.tcl
