// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="undistort_demo_hls_undistort_demo_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100-ffg900-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.389000,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1066,HLS_SYN_LUT=927,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module undistort_demo_hls (
        ap_clk,
        ap_rst_n,
        s_axis_TDATA,
        s_axis_TVALID,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST,
        m_axis_TDATA,
        m_axis_TVALID,
        m_axis_TREADY,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TLAST,
        algo_ctrl
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [63:0] s_axis_TDATA;
input   s_axis_TVALID;
output   s_axis_TREADY;
input  [7:0] s_axis_TKEEP;
input  [7:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;
output  [63:0] m_axis_TDATA;
output   m_axis_TVALID;
input   m_axis_TREADY;
output  [7:0] m_axis_TKEEP;
output  [7:0] m_axis_TSTRB;
output  [0:0] m_axis_TLAST;
input  [31:0] algo_ctrl;

 reg    ap_rst_n_inv;
reg   [0:0] in_payload;
reg   [0:0] frame_phase;
reg   [11:0] current_line;
reg   [3:0] current_packet;
reg   [5:0] payload_word_idx;
reg   [0:0] seen_line;
reg   [11:0] last_line;
reg    s_axis_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_grp1;
wire   [0:0] tmp_nbreadreq_fu_174_p6;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    m_axis_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] tmp_reg_1085;
reg   [0:0] tmp_reg_1085_pp0_iter2_reg;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] tmp_reg_1085_pp0_iter3_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_state4_pp0_stage0_iter3_grp1;
reg    ap_block_state5_pp0_stage0_iter4_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] tmp_reg_1085_pp0_iter1_reg;
reg   [63:0] in_word_data_reg_1089;
reg   [63:0] in_word_data_reg_1089_pp0_iter1_reg;
reg   [63:0] in_word_data_reg_1089_pp0_iter2_reg;
reg   [7:0] in_word_keep_reg_1099;
reg   [7:0] in_word_keep_reg_1099_pp0_iter1_reg;
reg   [7:0] in_word_keep_reg_1099_pp0_iter2_reg;
reg   [7:0] in_word_strb_reg_1104;
reg   [7:0] in_word_strb_reg_1104_pp0_iter1_reg;
reg   [7:0] in_word_strb_reg_1104_pp0_iter2_reg;
wire   [0:0] in_word_last_fu_255_p1;
reg   [0:0] in_word_last_reg_1109;
reg   [0:0] in_word_last_reg_1109_pp0_iter1_reg;
reg   [0:0] in_word_last_reg_1109_pp0_iter2_reg;
wire   [0:0] algo_enable_fu_259_p1;
reg   [0:0] algo_enable_reg_1114;
reg   [0:0] algo_enable_reg_1114_pp0_iter1_reg;
reg   [0:0] algo_enable_reg_1114_pp0_iter2_reg;
reg   [0:0] demo_enable_reg_1123;
reg   [0:0] demo_enable_reg_1123_pp0_iter1_reg;
reg   [0:0] demo_enable_reg_1123_pp0_iter2_reg;
wire   [0:0] in_payload_load_load_fu_279_p1;
reg   [0:0] in_payload_load_reg_1132;
reg   [0:0] in_payload_load_reg_1132_pp0_iter1_reg;
reg   [0:0] in_payload_load_reg_1132_pp0_iter2_reg;
reg   [11:0] lhs_reg_1136;
reg   [3:0] current_packet_load_reg_1144;
wire   [0:0] xor_ln73_fu_395_p2;
reg   [0:0] xor_ln73_reg_1155;
reg   [0:0] xor_ln73_reg_1155_pp0_iter1_reg;
wire   [0:0] phase_1_fu_401_p2;
reg   [0:0] phase_1_reg_1163;
wire   [15:0] select_ln46_fu_407_p3;
reg   [15:0] select_ln46_reg_1168;
reg   [15:0] select_ln46_reg_1168_pp0_iter1_reg;
reg   [15:0] select_ln46_reg_1168_pp0_iter2_reg;
wire   [11:0] base_x_fu_448_p2;
reg   [11:0] base_x_reg_1176;
wire   [0:0] icmp_ln5_1_fu_489_p2;
reg   [0:0] icmp_ln5_1_reg_1182;
wire   [10:0] trunc_ln5_fu_495_p1;
reg   [10:0] trunc_ln5_reg_1190;
wire   [10:0] dx_1_fu_499_p2;
reg   [10:0] dx_1_reg_1197;
wire   [11:0] dy_1_fu_505_p3;
reg   [11:0] dy_1_reg_1202;
wire   [0:0] xor_ln40_1_fu_534_p2;
reg   [0:0] xor_ln40_1_reg_1207;
reg   [0:0] xor_ln40_1_reg_1207_pp0_iter2_reg;
wire   [10:0] dx_4_fu_557_p2;
reg   [10:0] dx_4_reg_1215;
wire   [10:0] dx_7_fu_581_p2;
reg   [10:0] dx_7_reg_1220;
wire   [10:0] dx_10_fu_595_p2;
reg   [10:0] dx_10_reg_1225;
wire   [15:0] corrected_1_fu_708_p9;
reg   [15:0] corrected_1_reg_1230;
wire   [15:0] corrected_3_fu_804_p9;
reg   [15:0] corrected_3_reg_1236;
wire   [15:0] corrected_5_fu_900_p9;
reg   [15:0] corrected_5_reg_1242;
wire   [15:0] corrected_7_fu_996_p9;
reg   [15:0] corrected_7_reg_1248;
reg    ap_enable_reg_pp0_iter1;
wire    regslice_both_m_axis_V_data_V_U_apdone_blk;
reg    ap_enable_reg_pp0_iter2;
reg   [5:0] ap_phi_mux_payload_word_idx_new_1_phi_fu_219_p6;
wire   [5:0] ap_phi_reg_pp0_iter1_payload_word_idx_new_1_reg_216;
wire   [5:0] add_ln112_fu_601_p2;
reg   [63:0] ap_phi_mux_out_word_data_3_phi_fu_233_p6;
wire   [63:0] ap_phi_reg_pp0_iter0_out_word_data_3_reg_229;
reg   [63:0] ap_phi_reg_pp0_iter1_out_word_data_3_reg_229;
reg   [63:0] ap_phi_reg_pp0_iter2_out_word_data_3_reg_229;
reg   [63:0] ap_phi_reg_pp0_iter3_out_word_data_3_reg_229;
wire   [63:0] out_word_data_1_fu_1076_p3;
wire   [0:0] xor_ln93_fu_383_p2;
wire   [0:0] xor_ln84_fu_347_p2;
wire   [0:0] icmp_ln82_fu_315_p2;
wire   [0:0] and_ln83_1_fu_341_p2;
wire   [11:0] line_idx_fu_295_p4;
wire   [3:0] packet_idx_fu_305_p4;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] demo_frame_toggle_enable_fu_271_p3;
wire   [0:0] icmp_ln83_fu_329_p2;
wire   [0:0] and_ln83_fu_335_p2;
wire   [10:0] shl_ln_fu_425_p3;
wire   [7:0] shl_ln96_1_fu_436_p3;
wire   [11:0] zext_ln96_fu_432_p1;
wire   [11:0] zext_ln96_1_fu_444_p1;
wire   [1:0] tmp_5_fu_454_p4;
wire   [1:0] tmp_6_fu_479_p4;
wire   [0:0] icmp_ln5_fu_463_p2;
wire   [11:0] dy_fu_469_p2;
wire   [11:0] sub_ln5_fu_474_p2;
wire   [0:0] tmp_8_fu_513_p3;
wire   [0:0] tmp_9_fu_521_p3;
wire   [0:0] xor_ln40_fu_528_p2;
wire   [9:0] tmp_3_fu_539_p4;
wire   [10:0] or_ln5_fu_549_p3;
wire   [8:0] tmp_4_fu_563_p4;
wire   [10:0] or_ln5_1_fu_573_p3;
wire   [10:0] or_ln5_2_fu_587_p3;
wire   [0:0] bit_sel_fu_617_p3;
wire   [0:0] xor_ln5_fu_624_p2;
wire   [9:0] trunc_ln5_1_fu_630_p1;
wire   [10:0] dx_fu_633_p3;
wire   [10:0] dx_2_fu_641_p3;
wire   [12:0] zext_ln23_fu_647_p1;
wire   [12:0] zext_ln23_1_fu_651_p1;
wire   [12:0] add_ln23_fu_654_p2;
wire   [15:0] pixel_fu_614_p1;
wire   [5:0] radial_gain_fu_660_p4;
wire   [16:0] zext_ln24_fu_670_p1;
wire   [16:0] zext_ln24_1_fu_674_p1;
wire   [16:0] compensated_fu_678_p2;
wire   [0:0] tmp_7_fu_684_p3;
wire   [0:0] and_ln25_fu_696_p2;
wire   [15:0] corrected_1_fu_708_p6;
wire   [15:0] corrected_1_fu_708_p7;
wire   [1:0] corrected_1_fu_708_p8;
wire   [10:0] dx_3_fu_735_p2;
wire   [10:0] dx_5_fu_740_p3;
wire   [12:0] zext_ln23_2_fu_746_p1;
wire   [12:0] add_ln23_1_fu_750_p2;
wire   [15:0] pixel_1_fu_728_p3;
wire   [5:0] radial_gain_1_fu_756_p4;
wire   [16:0] zext_ln24_2_fu_766_p1;
wire   [16:0] zext_ln24_3_fu_770_p1;
wire   [16:0] compensated_1_fu_774_p2;
wire   [0:0] tmp_10_fu_780_p3;
wire   [0:0] and_ln25_1_fu_792_p2;
wire   [15:0] corrected_3_fu_804_p2;
wire   [15:0] corrected_3_fu_804_p6;
wire   [15:0] corrected_3_fu_804_p7;
wire   [1:0] corrected_3_fu_804_p8;
wire   [10:0] dx_6_fu_831_p2;
wire   [10:0] dx_8_fu_836_p3;
wire   [12:0] zext_ln23_3_fu_842_p1;
wire   [12:0] add_ln23_2_fu_846_p2;
wire   [15:0] pixel_2_fu_824_p3;
wire   [5:0] radial_gain_2_fu_852_p4;
wire   [16:0] zext_ln24_4_fu_862_p1;
wire   [16:0] zext_ln24_5_fu_866_p1;
wire   [16:0] compensated_2_fu_870_p2;
wire   [0:0] tmp_11_fu_876_p3;
wire   [0:0] and_ln25_2_fu_888_p2;
wire   [15:0] corrected_5_fu_900_p2;
wire   [15:0] corrected_5_fu_900_p6;
wire   [15:0] corrected_5_fu_900_p7;
wire   [1:0] corrected_5_fu_900_p8;
wire   [10:0] dx_9_fu_927_p2;
wire   [10:0] dx_11_fu_932_p3;
wire   [12:0] zext_ln23_4_fu_938_p1;
wire   [12:0] add_ln23_3_fu_942_p2;
wire   [15:0] pixel_3_fu_920_p3;
wire   [5:0] radial_gain_3_fu_948_p4;
wire   [16:0] zext_ln24_6_fu_958_p1;
wire   [16:0] zext_ln24_7_fu_962_p1;
wire   [16:0] compensated_3_fu_966_p2;
wire   [0:0] tmp_12_fu_972_p3;
wire   [0:0] and_ln25_3_fu_984_p2;
wire   [15:0] corrected_7_fu_996_p2;
wire   [15:0] corrected_7_fu_996_p6;
wire   [15:0] corrected_7_fu_996_p7;
wire   [1:0] corrected_7_fu_996_p8;
wire   [15:0] select_ln42_fu_1020_p3;
wire   [15:0] select_ln42_1_fu_1031_p3;
wire   [15:0] select_ln42_2_fu_1042_p3;
wire   [15:0] select_ln42_3_fu_1053_p3;
wire   [15:0] demo_pixel_3_fu_1058_p3;
wire   [15:0] demo_pixel_2_fu_1047_p3;
wire   [15:0] demo_pixel_1_fu_1036_p3;
wire   [15:0] demo_pixel_fu_1025_p3;
wire   [0:0] or_ln95_fu_1016_p2;
wire   [63:0] out_word_data_2_fu_1064_p5;
reg   [0:0] ap_NS_fsm;
wire    ap_idle_pp0_0to3;
reg    ap_reset_init_pp0;
reg    ap_block_pp0_stage0_11001;
wire    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_s_axis_V_data_V_U_apdone_blk;
wire   [63:0] s_axis_TDATA_int_regslice;
wire    s_axis_TVALID_int_regslice;
reg    s_axis_TREADY_int_regslice;
wire    regslice_both_s_axis_V_data_V_U_ack_in;
wire    regslice_both_s_axis_V_keep_V_U_apdone_blk;
wire   [7:0] s_axis_TKEEP_int_regslice;
wire    regslice_both_s_axis_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_V_strb_V_U_apdone_blk;
wire   [7:0] s_axis_TSTRB_int_regslice;
wire    regslice_both_s_axis_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_TLAST_int_regslice;
wire    regslice_both_s_axis_V_last_V_U_vld_out;
wire    regslice_both_s_axis_V_last_V_U_ack_in;
reg    m_axis_TVALID_int_regslice;
wire    m_axis_TREADY_int_regslice;
wire    regslice_both_m_axis_V_data_V_U_vld_out;
wire    regslice_both_m_axis_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_last_V_U_vld_out;
reg    ap_condition_214;
reg    ap_condition_904;
wire  signed [1:0] corrected_1_fu_708_p1;
wire   [1:0] corrected_1_fu_708_p3;
wire   [1:0] corrected_1_fu_708_p5;
wire  signed [1:0] corrected_3_fu_804_p1;
wire   [1:0] corrected_3_fu_804_p3;
wire   [1:0] corrected_3_fu_804_p5;
wire  signed [1:0] corrected_5_fu_900_p1;
wire   [1:0] corrected_5_fu_900_p3;
wire   [1:0] corrected_5_fu_900_p5;
wire  signed [1:0] corrected_7_fu_996_p1;
wire   [1:0] corrected_7_fu_996_p3;
wire   [1:0] corrected_7_fu_996_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 in_payload = 1'd0;
#0 frame_phase = 1'd0;
#0 current_line = 12'd0;
#0 current_packet = 4'd0;
#0 payload_word_idx = 6'd0;
#0 seen_line = 1'd0;
#0 last_line = 12'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

(* dissolve_hierarchy = "yes" *) undistort_demo_hls_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U1(
    .din0(pixel_fu_614_p1),
    .din1(16'd65535),
    .din2(corrected_1_fu_708_p6),
    .def(corrected_1_fu_708_p7),
    .sel(corrected_1_fu_708_p8),
    .dout(corrected_1_fu_708_p9)
);

(* dissolve_hierarchy = "yes" *) undistort_demo_hls_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U2(
    .din0(corrected_3_fu_804_p2),
    .din1(16'd65535),
    .din2(corrected_3_fu_804_p6),
    .def(corrected_3_fu_804_p7),
    .sel(corrected_3_fu_804_p8),
    .dout(corrected_3_fu_804_p9)
);

(* dissolve_hierarchy = "yes" *) undistort_demo_hls_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U3(
    .din0(corrected_5_fu_900_p2),
    .din1(16'd65535),
    .din2(corrected_5_fu_900_p6),
    .def(corrected_5_fu_900_p7),
    .sel(corrected_5_fu_900_p8),
    .dout(corrected_5_fu_900_p9)
);

(* dissolve_hierarchy = "yes" *) undistort_demo_hls_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U4(
    .din0(corrected_7_fu_996_p2),
    .din1(16'd65535),
    .din2(corrected_7_fu_996_p6),
    .def(corrected_7_fu_996_p7),
    .sel(corrected_7_fu_996_p8),
    .dout(corrected_7_fu_996_p9)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TDATA),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_data_V_U_ack_in),
    .data_out(s_axis_TDATA_int_regslice),
    .vld_out(s_axis_TVALID_int_regslice),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_data_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TKEEP),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_keep_V_U_ack_in),
    .data_out(s_axis_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_V_keep_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_keep_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TSTRB),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_strb_V_U_ack_in),
    .data_out(s_axis_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_V_strb_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_strb_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TLAST),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_last_V_U_ack_in),
    .data_out(s_axis_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_V_last_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_last_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 64 ))
regslice_both_m_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(ap_phi_mux_out_word_data_3_phi_fu_233_p6),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(m_axis_TREADY_int_regslice),
    .data_out(m_axis_TDATA),
    .vld_out(regslice_both_m_axis_V_data_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_data_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 8 ))
regslice_both_m_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_word_keep_reg_1099_pp0_iter2_reg),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_TKEEP),
    .vld_out(regslice_both_m_axis_V_keep_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_keep_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 8 ))
regslice_both_m_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_word_strb_reg_1104_pp0_iter2_reg),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_TSTRB),
    .vld_out(regslice_both_m_axis_V_strb_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_strb_V_U_apdone_blk)
);

undistort_demo_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_word_last_reg_1109_pp0_iter2_reg),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_TLAST),
    .vld_out(regslice_both_m_axis_V_last_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_214)) begin
        if (((tmp_reg_1085 == 1'd1) & (in_payload_load_reg_1132 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_out_word_data_3_reg_229 <= in_word_data_reg_1089;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_out_word_data_3_reg_229 <= ap_phi_reg_pp0_iter1_out_word_data_3_reg_229;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_904)) begin
        if (((in_payload_load_load_fu_279_p1 == 1'd1) & (in_word_last_fu_255_p1 == 1'd1))) begin
            in_payload <= 1'd0;
        end else if ((in_payload_load_load_fu_279_p1 == 1'd0)) begin
            in_payload <= xor_ln93_fu_383_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        algo_enable_reg_1114 <= algo_enable_fu_259_p1;
        ap_phi_reg_pp0_iter1_out_word_data_3_reg_229 <= ap_phi_reg_pp0_iter0_out_word_data_3_reg_229;
        current_packet_load_reg_1144 <= current_packet;
        demo_enable_reg_1123 <= algo_ctrl[32'd1];
        in_payload_load_reg_1132 <= in_payload;
        in_word_data_reg_1089 <= s_axis_TDATA_int_regslice;
        in_word_keep_reg_1099 <= s_axis_TKEEP_int_regslice;
        in_word_last_reg_1109 <= s_axis_TLAST_int_regslice;
        in_word_strb_reg_1104 <= s_axis_TSTRB_int_regslice;
        lhs_reg_1136 <= current_line;
        phase_1_reg_1163 <= phase_1_fu_401_p2;
        select_ln46_reg_1168 <= select_ln46_fu_407_p3;
        tmp_reg_1085 <= tmp_nbreadreq_fu_174_p6;
        xor_ln73_reg_1155 <= xor_ln73_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        algo_enable_reg_1114_pp0_iter1_reg <= algo_enable_reg_1114;
        base_x_reg_1176[11 : 2] <= base_x_fu_448_p2[11 : 2];
        demo_enable_reg_1123_pp0_iter1_reg <= demo_enable_reg_1123;
        dx_10_reg_1225[10 : 2] <= dx_10_fu_595_p2[10 : 2];
        dx_1_reg_1197[10 : 2] <= dx_1_fu_499_p2[10 : 2];
        dx_4_reg_1215[10 : 2] <= dx_4_fu_557_p2[10 : 2];
        dx_7_reg_1220[10 : 2] <= dx_7_fu_581_p2[10 : 2];
        dy_1_reg_1202 <= dy_1_fu_505_p3;
        icmp_ln5_1_reg_1182 <= icmp_ln5_1_fu_489_p2;
        in_payload_load_reg_1132_pp0_iter1_reg <= in_payload_load_reg_1132;
        in_word_data_reg_1089_pp0_iter1_reg <= in_word_data_reg_1089;
        in_word_keep_reg_1099_pp0_iter1_reg <= in_word_keep_reg_1099;
        in_word_last_reg_1109_pp0_iter1_reg <= in_word_last_reg_1109;
        in_word_strb_reg_1104_pp0_iter1_reg <= in_word_strb_reg_1104;
        select_ln46_reg_1168_pp0_iter1_reg <= select_ln46_reg_1168;
        tmp_reg_1085_pp0_iter1_reg <= tmp_reg_1085;
        trunc_ln5_reg_1190[10 : 2] <= trunc_ln5_fu_495_p1[10 : 2];
        xor_ln40_1_reg_1207 <= xor_ln40_1_fu_534_p2;
        xor_ln73_reg_1155_pp0_iter1_reg <= xor_ln73_reg_1155;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        algo_enable_reg_1114_pp0_iter2_reg <= algo_enable_reg_1114_pp0_iter1_reg;
        corrected_1_reg_1230 <= corrected_1_fu_708_p9;
        corrected_3_reg_1236 <= corrected_3_fu_804_p9;
        corrected_5_reg_1242 <= corrected_5_fu_900_p9;
        corrected_7_reg_1248 <= corrected_7_fu_996_p9;
        demo_enable_reg_1123_pp0_iter2_reg <= demo_enable_reg_1123_pp0_iter1_reg;
        in_payload_load_reg_1132_pp0_iter2_reg <= in_payload_load_reg_1132_pp0_iter1_reg;
        in_word_data_reg_1089_pp0_iter2_reg <= in_word_data_reg_1089_pp0_iter1_reg;
        in_word_keep_reg_1099_pp0_iter2_reg <= in_word_keep_reg_1099_pp0_iter1_reg;
        in_word_last_reg_1109_pp0_iter2_reg <= in_word_last_reg_1109_pp0_iter1_reg;
        in_word_strb_reg_1104_pp0_iter2_reg <= in_word_strb_reg_1104_pp0_iter1_reg;
        select_ln46_reg_1168_pp0_iter2_reg <= select_ln46_reg_1168_pp0_iter1_reg;
        tmp_reg_1085_pp0_iter2_reg <= tmp_reg_1085_pp0_iter1_reg;
        tmp_reg_1085_pp0_iter3_reg <= tmp_reg_1085_pp0_iter2_reg;
        xor_ln40_1_reg_1207_pp0_iter2_reg <= xor_ln40_1_reg_1207;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_out_word_data_3_reg_229 <= ap_phi_reg_pp0_iter2_out_word_data_3_reg_229;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_174_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (in_payload_load_load_fu_279_p1 == 1'd0))) begin
        current_line <= {{s_axis_TDATA_int_regslice[23:12]}};
        current_packet <= {{s_axis_TDATA_int_regslice[11:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln83_1_fu_341_p2) & (tmp_nbreadreq_fu_174_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln82_fu_315_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (in_payload_load_load_fu_279_p1 == 1'd0))) begin
        frame_phase <= xor_ln84_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_174_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln82_fu_315_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (in_payload_load_load_fu_279_p1 == 1'd0))) begin
        last_line <= {{s_axis_TDATA_int_regslice[23:12]}};
        seen_line <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        payload_word_idx <= ap_phi_mux_payload_word_idx_new_1_phi_fu_219_p6;
    end
end

assign ap_idle_pp0 = 1'b0;

assign ap_idle_pp0_0to3 = 1'b0;

always @ (*) begin
    if ((((tmp_reg_1085_pp0_iter2_reg == 1'd1) & (in_payload_load_reg_1132_pp0_iter2_reg == 1'd1) & (in_word_last_reg_1109_pp0_iter2_reg == 1'd0)) | ((tmp_reg_1085_pp0_iter2_reg == 1'd1) & (in_payload_load_reg_1132_pp0_iter2_reg == 1'd1) & (in_word_last_reg_1109_pp0_iter2_reg == 1'd1)))) begin
        ap_phi_mux_out_word_data_3_phi_fu_233_p6 = out_word_data_1_fu_1076_p3;
    end else begin
        ap_phi_mux_out_word_data_3_phi_fu_233_p6 = ap_phi_reg_pp0_iter3_out_word_data_3_reg_229;
    end
end

always @ (*) begin
    if (((tmp_reg_1085 == 1'd1) & (in_payload_load_reg_1132 == 1'd1) & (in_word_last_reg_1109 == 1'd0))) begin
        ap_phi_mux_payload_word_idx_new_1_phi_fu_219_p6 = add_ln112_fu_601_p2;
    end else if ((((tmp_reg_1085 == 1'd1) & (in_payload_load_reg_1132 == 1'd1) & (in_word_last_reg_1109 == 1'd1)) | ((tmp_reg_1085 == 1'd1) & (in_payload_load_reg_1132 == 1'd0)))) begin
        ap_phi_mux_payload_word_idx_new_1_phi_fu_219_p6 = 6'd0;
    end else begin
        ap_phi_mux_payload_word_idx_new_1_phi_fu_219_p6 = ap_phi_reg_pp0_iter1_payload_word_idx_new_1_reg_216;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to3 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_1085_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((tmp_reg_1085_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1)))) begin
        m_axis_TDATA_blk_n = m_axis_TREADY_int_regslice;
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_reg_1085_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axis_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_174_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID_int_regslice;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_174_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln112_fu_601_p2 = (payload_word_idx + 6'd1);

assign add_ln23_1_fu_750_p2 = (zext_ln23_2_fu_746_p1 + zext_ln23_1_fu_651_p1);

assign add_ln23_2_fu_846_p2 = (zext_ln23_3_fu_842_p1 + zext_ln23_1_fu_651_p1);

assign add_ln23_3_fu_942_p2 = (zext_ln23_4_fu_938_p1 + zext_ln23_1_fu_651_p1);

assign add_ln23_fu_654_p2 = (zext_ln23_fu_647_p1 + zext_ln23_1_fu_651_p1);

assign algo_enable_fu_259_p1 = algo_ctrl[0:0];

assign and_ln25_1_fu_792_p2 = (tmp_10_fu_780_p3 & algo_enable_reg_1114_pp0_iter1_reg);

assign and_ln25_2_fu_888_p2 = (tmp_11_fu_876_p3 & algo_enable_reg_1114_pp0_iter1_reg);

assign and_ln25_3_fu_984_p2 = (tmp_12_fu_972_p3 & algo_enable_reg_1114_pp0_iter1_reg);

assign and_ln25_fu_696_p2 = (tmp_7_fu_684_p3 & algo_enable_reg_1114_pp0_iter1_reg);

assign and_ln83_1_fu_341_p2 = (seen_line & and_ln83_fu_335_p2);

assign and_ln83_fu_335_p2 = (icmp_ln83_fu_329_p2 & demo_frame_toggle_enable_fu_271_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((s_axis_TVALID_int_regslice == 1'b0) & (tmp_nbreadreq_fu_174_p6 == 1'd1));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3_grp1 = ((m_axis_TREADY_int_regslice == 1'b0) & (tmp_reg_1085_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4_grp1 = ((m_axis_TREADY_int_regslice == 1'b0) & (tmp_reg_1085_pp0_iter3_reg == 1'd1));
end

always @ (*) begin
    ap_condition_214 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_904 = ((tmp_nbreadreq_fu_174_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_out_word_data_3_reg_229 = 'bx;

assign ap_phi_reg_pp0_iter1_payload_word_idx_new_1_reg_216 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign base_x_fu_448_p2 = (zext_ln96_fu_432_p1 + zext_ln96_1_fu_444_p1);

assign bit_sel_fu_617_p3 = base_x_reg_1176[32'd10];

assign compensated_1_fu_774_p2 = (zext_ln24_2_fu_766_p1 + zext_ln24_3_fu_770_p1);

assign compensated_2_fu_870_p2 = (zext_ln24_4_fu_862_p1 + zext_ln24_5_fu_866_p1);

assign compensated_3_fu_966_p2 = (zext_ln24_6_fu_958_p1 + zext_ln24_7_fu_962_p1);

assign compensated_fu_678_p2 = (zext_ln24_fu_670_p1 + zext_ln24_1_fu_674_p1);

assign corrected_1_fu_708_p6 = compensated_fu_678_p2[15:0];

assign corrected_1_fu_708_p7 = 'bx;

assign corrected_1_fu_708_p8 = {{xor_ln73_reg_1155_pp0_iter1_reg}, {and_ln25_fu_696_p2}};

assign corrected_3_fu_804_p2 = {{in_word_data_reg_1089_pp0_iter1_reg[31:16]}};

assign corrected_3_fu_804_p6 = compensated_1_fu_774_p2[15:0];

assign corrected_3_fu_804_p7 = 'bx;

assign corrected_3_fu_804_p8 = {{xor_ln73_reg_1155_pp0_iter1_reg}, {and_ln25_1_fu_792_p2}};

assign corrected_5_fu_900_p2 = {{in_word_data_reg_1089_pp0_iter1_reg[47:32]}};

assign corrected_5_fu_900_p6 = compensated_2_fu_870_p2[15:0];

assign corrected_5_fu_900_p7 = 'bx;

assign corrected_5_fu_900_p8 = {{xor_ln73_reg_1155_pp0_iter1_reg}, {and_ln25_2_fu_888_p2}};

assign corrected_7_fu_996_p2 = {{in_word_data_reg_1089_pp0_iter1_reg[63:48]}};

assign corrected_7_fu_996_p6 = compensated_3_fu_966_p2[15:0];

assign corrected_7_fu_996_p7 = 'bx;

assign corrected_7_fu_996_p8 = {{xor_ln73_reg_1155_pp0_iter1_reg}, {and_ln25_3_fu_984_p2}};

assign demo_frame_toggle_enable_fu_271_p3 = algo_ctrl[32'd2];

assign demo_pixel_1_fu_1036_p3 = ((demo_enable_reg_1123_pp0_iter2_reg[0:0] == 1'b1) ? select_ln42_1_fu_1031_p3 : corrected_3_reg_1236);

assign demo_pixel_2_fu_1047_p3 = ((demo_enable_reg_1123_pp0_iter2_reg[0:0] == 1'b1) ? select_ln42_2_fu_1042_p3 : corrected_5_reg_1242);

assign demo_pixel_3_fu_1058_p3 = ((demo_enable_reg_1123_pp0_iter2_reg[0:0] == 1'b1) ? select_ln42_3_fu_1053_p3 : corrected_7_reg_1248);

assign demo_pixel_fu_1025_p3 = ((demo_enable_reg_1123_pp0_iter2_reg[0:0] == 1'b1) ? select_ln42_fu_1020_p3 : corrected_1_reg_1230);

assign dx_10_fu_595_p2 = ($signed(11'd1024) - $signed(or_ln5_2_fu_587_p3));

assign dx_11_fu_932_p3 = ((icmp_ln5_1_reg_1182[0:0] == 1'b1) ? dx_9_fu_927_p2 : dx_10_reg_1225);

assign dx_1_fu_499_p2 = ($signed(11'd1024) - $signed(trunc_ln5_fu_495_p1));

assign dx_2_fu_641_p3 = ((icmp_ln5_1_reg_1182[0:0] == 1'b1) ? dx_fu_633_p3 : dx_1_reg_1197);

assign dx_3_fu_735_p2 = (trunc_ln5_reg_1190 ^ 11'd1025);

assign dx_4_fu_557_p2 = ($signed(11'd1024) - $signed(or_ln5_fu_549_p3));

assign dx_5_fu_740_p3 = ((icmp_ln5_1_reg_1182[0:0] == 1'b1) ? dx_3_fu_735_p2 : dx_4_reg_1215);

assign dx_6_fu_831_p2 = (trunc_ln5_reg_1190 ^ 11'd1026);

assign dx_7_fu_581_p2 = ($signed(11'd1024) - $signed(or_ln5_1_fu_573_p3));

assign dx_8_fu_836_p3 = ((icmp_ln5_1_reg_1182[0:0] == 1'b1) ? dx_6_fu_831_p2 : dx_7_reg_1220);

assign dx_9_fu_927_p2 = (trunc_ln5_reg_1190 ^ 11'd1027);

assign dx_fu_633_p3 = {{xor_ln5_fu_624_p2}, {trunc_ln5_1_fu_630_p1}};

assign dy_1_fu_505_p3 = ((icmp_ln5_fu_463_p2[0:0] == 1'b1) ? dy_fu_469_p2 : sub_ln5_fu_474_p2);

assign dy_fu_469_p2 = ($signed(lhs_reg_1136) + $signed(12'd3072));

assign icmp_ln5_1_fu_489_p2 = ((tmp_6_fu_479_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln5_fu_463_p2 = ((tmp_5_fu_454_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_315_p2 = ((packet_idx_fu_305_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_329_p2 = ((line_idx_fu_295_p4 < last_line) ? 1'b1 : 1'b0);

assign in_payload_load_load_fu_279_p1 = in_payload;

assign in_word_last_fu_255_p1 = s_axis_TLAST_int_regslice;

assign line_idx_fu_295_p4 = {{s_axis_TDATA_int_regslice[23:12]}};

assign m_axis_TVALID = regslice_both_m_axis_V_data_V_U_vld_out;

assign or_ln5_1_fu_573_p3 = {{tmp_4_fu_563_p4}, {2'd2}};

assign or_ln5_2_fu_587_p3 = {{tmp_4_fu_563_p4}, {2'd3}};

assign or_ln5_fu_549_p3 = {{tmp_3_fu_539_p4}, {1'd1}};

assign or_ln95_fu_1016_p2 = (demo_enable_reg_1123_pp0_iter2_reg | algo_enable_reg_1114_pp0_iter2_reg);

assign out_word_data_1_fu_1076_p3 = ((or_ln95_fu_1016_p2[0:0] == 1'b1) ? out_word_data_2_fu_1064_p5 : in_word_data_reg_1089_pp0_iter2_reg);

assign out_word_data_2_fu_1064_p5 = {{{{demo_pixel_3_fu_1058_p3}, {demo_pixel_2_fu_1047_p3}}, {demo_pixel_1_fu_1036_p3}}, {demo_pixel_fu_1025_p3}};

assign packet_idx_fu_305_p4 = {{s_axis_TDATA_int_regslice[11:8]}};

assign phase_1_fu_401_p2 = (frame_phase & demo_frame_toggle_enable_fu_271_p3);

assign pixel_1_fu_728_p3 = {{in_word_data_reg_1089_pp0_iter1_reg[31:16]}};

assign pixel_2_fu_824_p3 = {{in_word_data_reg_1089_pp0_iter1_reg[47:32]}};

assign pixel_3_fu_920_p3 = {{in_word_data_reg_1089_pp0_iter1_reg[63:48]}};

assign pixel_fu_614_p1 = in_word_data_reg_1089_pp0_iter1_reg[15:0];

assign radial_gain_1_fu_756_p4 = {{add_ln23_1_fu_750_p2[12:7]}};

assign radial_gain_2_fu_852_p4 = {{add_ln23_2_fu_846_p2[12:7]}};

assign radial_gain_3_fu_948_p4 = {{add_ln23_3_fu_942_p2[12:7]}};

assign radial_gain_fu_660_p4 = {{add_ln23_fu_654_p2[12:7]}};

assign s_axis_TREADY = regslice_both_s_axis_V_data_V_U_ack_in;

assign select_ln42_1_fu_1031_p3 = ((xor_ln40_1_reg_1207_pp0_iter2_reg[0:0] == 1'b1) ? corrected_3_reg_1236 : select_ln46_reg_1168_pp0_iter2_reg);

assign select_ln42_2_fu_1042_p3 = ((xor_ln40_1_reg_1207_pp0_iter2_reg[0:0] == 1'b1) ? corrected_5_reg_1242 : select_ln46_reg_1168_pp0_iter2_reg);

assign select_ln42_3_fu_1053_p3 = ((xor_ln40_1_reg_1207_pp0_iter2_reg[0:0] == 1'b1) ? corrected_7_reg_1248 : select_ln46_reg_1168_pp0_iter2_reg);

assign select_ln42_fu_1020_p3 = ((xor_ln40_1_reg_1207_pp0_iter2_reg[0:0] == 1'b1) ? corrected_1_reg_1230 : select_ln46_reg_1168_pp0_iter2_reg);

assign select_ln46_fu_407_p3 = ((phase_1_fu_401_p2[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign shl_ln96_1_fu_436_p3 = {{payload_word_idx}, {2'd0}};

assign shl_ln_fu_425_p3 = {{current_packet_load_reg_1144}, {7'd0}};

assign sub_ln5_fu_474_p2 = (12'd1024 - lhs_reg_1136);

assign tmp_10_fu_780_p3 = compensated_1_fu_774_p2[32'd16];

assign tmp_11_fu_876_p3 = compensated_2_fu_870_p2[32'd16];

assign tmp_12_fu_972_p3 = compensated_3_fu_966_p2[32'd16];

assign tmp_3_fu_539_p4 = {{base_x_fu_448_p2[10:1]}};

assign tmp_4_fu_563_p4 = {{base_x_fu_448_p2[10:2]}};

assign tmp_5_fu_454_p4 = {{lhs_reg_1136[11:10]}};

assign tmp_6_fu_479_p4 = {{base_x_fu_448_p2[11:10]}};

assign tmp_7_fu_684_p3 = compensated_fu_678_p2[32'd16];

assign tmp_8_fu_513_p3 = base_x_fu_448_p2[32'd7];

assign tmp_9_fu_521_p3 = lhs_reg_1136[32'd7];

assign tmp_nbreadreq_fu_174_p6 = s_axis_TVALID_int_regslice;

assign trunc_ln5_1_fu_630_p1 = base_x_reg_1176[9:0];

assign trunc_ln5_fu_495_p1 = base_x_fu_448_p2[10:0];

assign xor_ln40_1_fu_534_p2 = (xor_ln40_fu_528_p2 ^ phase_1_reg_1163);

assign xor_ln40_fu_528_p2 = (tmp_9_fu_521_p3 ^ tmp_8_fu_513_p3);

assign xor_ln5_fu_624_p2 = (bit_sel_fu_617_p3 ^ 1'd1);

assign xor_ln73_fu_395_p2 = (1'd1 ^ algo_enable_fu_259_p1);

assign xor_ln84_fu_347_p2 = (frame_phase ^ 1'd1);

assign xor_ln93_fu_383_p2 = (s_axis_TLAST_int_regslice ^ 1'd1);

assign zext_ln23_1_fu_651_p1 = dy_1_reg_1202;

assign zext_ln23_2_fu_746_p1 = dx_5_fu_740_p3;

assign zext_ln23_3_fu_842_p1 = dx_8_fu_836_p3;

assign zext_ln23_4_fu_938_p1 = dx_11_fu_932_p3;

assign zext_ln23_fu_647_p1 = dx_2_fu_641_p3;

assign zext_ln24_1_fu_674_p1 = radial_gain_fu_660_p4;

assign zext_ln24_2_fu_766_p1 = pixel_1_fu_728_p3;

assign zext_ln24_3_fu_770_p1 = radial_gain_1_fu_756_p4;

assign zext_ln24_4_fu_862_p1 = pixel_2_fu_824_p3;

assign zext_ln24_5_fu_866_p1 = radial_gain_2_fu_852_p4;

assign zext_ln24_6_fu_958_p1 = pixel_3_fu_920_p3;

assign zext_ln24_7_fu_962_p1 = radial_gain_3_fu_948_p4;

assign zext_ln24_fu_670_p1 = pixel_fu_614_p1;

assign zext_ln96_1_fu_444_p1 = shl_ln96_1_fu_436_p3;

assign zext_ln96_fu_432_p1 = shl_ln_fu_425_p3;

always @ (posedge ap_clk) begin
    base_x_reg_1176[1:0] <= 2'b00;
    trunc_ln5_reg_1190[1:0] <= 2'b00;
    dx_1_reg_1197[1:0] <= 2'b00;
    dx_4_reg_1215[1:0] <= 2'b11;
    dx_7_reg_1220[1:0] <= 2'b10;
    dx_10_reg_1225[1:0] <= 2'b01;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "undistort_demo_hls_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //undistort_demo_hls

