// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* CORE_GENERATION_INFO="fisheye_remap_addr_hls_fisheye_remap_addr_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100-ffg900-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.843000,HLS_SYN_LAT=18,HLS_SYN_TPT=1,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1804,HLS_SYN_LUT=1128,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module fisheye_remap_addr_hls (
        ap_clk,
        ap_rst,
        in_valid,
        out_x,
        out_line,
        out_slot,
        packet_pixel_idx,
        algo_ctrl,
        out_valid,
        src_slot,
        src_x,
        packet_pixel_idx_out
);


input   ap_clk;
input   ap_rst;
input  [0:0] in_valid;
input  [10:0] out_x;
input  [11:0] out_line;
input  [8:0] out_slot;
input  [6:0] packet_pixel_idx;
input  [31:0] algo_ctrl;
output  [0:0] out_valid;
output  [8:0] src_slot;
output  [10:0] src_x;
output  [6:0] packet_pixel_idx_out;

wire   [6:0] kLaserScaleQ16_address0;
wire   [16:0] kLaserScaleQ16_q0;
wire   [6:0] kInfraredScaleQ16_address0;
wire   [16:0] kInfraredScaleQ16_q0;
reg   [6:0] packet_pixel_idx_read_reg_1056;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter1_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter2_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter3_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter4_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter5_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter6_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter7_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter8_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter9_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter10_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter11_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter12_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter13_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter14_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter15_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter16_reg;
reg   [6:0] packet_pixel_idx_read_reg_1056_pp0_iter17_reg;
reg   [10:0] out_x_read_reg_1061;
reg   [10:0] out_x_read_reg_1061_pp0_iter1_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter2_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter3_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter4_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter5_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter6_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter7_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter8_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter9_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter10_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter11_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter12_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter13_reg;
reg   [10:0] out_x_read_reg_1061_pp0_iter14_reg;
reg   [0:0] in_valid_read_reg_1066;
reg   [0:0] in_valid_read_reg_1066_pp0_iter1_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter2_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter3_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter4_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter5_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter6_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter7_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter8_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter9_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter10_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter11_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter12_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter13_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter14_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter15_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter16_reg;
reg   [0:0] in_valid_read_reg_1066_pp0_iter17_reg;
wire   [7:0] out_slot_1_fu_306_p1;
reg   [7:0] out_slot_1_reg_1073;
reg   [7:0] out_slot_1_reg_1073_pp0_iter1_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter2_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter3_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter4_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter5_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter6_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter7_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter8_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter9_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter10_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter11_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter12_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter13_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter14_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter15_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter16_reg;
reg   [7:0] out_slot_1_reg_1073_pp0_iter17_reg;
wire   [0:0] trunc_ln190_fu_310_p1;
reg   [0:0] trunc_ln190_reg_1079;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter1_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter2_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter3_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter4_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter5_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter6_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter7_reg;
reg   [0:0] trunc_ln190_reg_1079_pp0_iter8_reg;
wire   [11:0] zext_ln196_fu_314_p1;
reg   [11:0] zext_ln196_reg_1084;
reg   [11:0] zext_ln196_reg_1084_pp0_iter1_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter2_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter3_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter4_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter5_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter6_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter7_reg;
reg   [11:0] zext_ln196_reg_1084_pp0_iter8_reg;
wire  signed [11:0] dx_fu_318_p2;
reg  signed [11:0] dx_reg_1090;
reg  signed [11:0] dx_reg_1090_pp0_iter1_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter2_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter3_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter4_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter5_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter6_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter7_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter8_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter9_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter10_reg;
reg  signed [11:0] dx_reg_1090_pp0_iter11_reg;
wire   [12:0] zext_ln197_fu_324_p1;
reg   [12:0] zext_ln197_reg_1095;
reg   [12:0] zext_ln197_reg_1095_pp0_iter1_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter2_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter3_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter4_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter5_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter6_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter7_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter8_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter9_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter10_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter11_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter12_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter13_reg;
reg   [12:0] zext_ln197_reg_1095_pp0_iter14_reg;
wire  signed [12:0] dy_fu_328_p2;
reg  signed [12:0] dy_reg_1102;
reg  signed [12:0] dy_reg_1102_pp0_iter1_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter2_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter3_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter4_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter5_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter6_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter7_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter8_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter9_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter10_reg;
reg  signed [12:0] dy_reg_1102_pp0_iter11_reg;
wire   [11:0] select_ln34_fu_348_p3;
reg   [11:0] select_ln34_reg_1107;
wire   [12:0] delta_fu_370_p3;
reg   [12:0] delta_reg_1112;
reg   [12:0] delta_reg_1112_pp0_iter1_reg;
reg   [12:0] delta_reg_1112_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_1119;
reg   [0:0] tmp_4_reg_1119_pp0_iter1_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter6_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter7_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter8_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter9_reg;
reg   [0:0] tmp_4_reg_1119_pp0_iter10_reg;
wire   [0:0] icmp_ln135_fu_386_p2;
reg   [0:0] icmp_ln135_reg_1124;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter2_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter3_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter4_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter5_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter6_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter7_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter8_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter9_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter10_reg;
reg   [0:0] icmp_ln135_reg_1124_pp0_iter11_reg;
wire  signed [12:0] sext_ln32_fu_392_p1;
reg  signed [12:0] sext_ln32_reg_1129;
reg  signed [12:0] sext_ln32_reg_1129_pp0_iter2_reg;
wire   [0:0] icmp_ln61_fu_395_p2;
reg   [0:0] icmp_ln61_reg_1135;
reg   [0:0] icmp_ln61_reg_1135_pp0_iter2_reg;
wire   [14:0] sub_ln63_fu_417_p2;
reg   [14:0] sub_ln63_reg_1141;
wire   [13:0] radius_fu_445_p2;
reg   [13:0] radius_reg_1146;
wire   [9:0] radius_1_fu_451_p1;
reg   [9:0] radius_1_reg_1151;
wire   [9:0] radius_2_fu_460_p3;
reg   [9:0] radius_2_reg_1156;
reg   [9:0] radius_2_reg_1156_pp0_iter5_reg;
reg   [9:0] radius_2_reg_1156_pp0_iter6_reg;
wire   [10:0] sub_ln74_fu_470_p2;
reg   [10:0] sub_ln74_reg_1163;
wire   [13:0] sub_ln74_1_fu_490_p2;
reg   [13:0] sub_ln74_1_reg_1168;
reg   [6:0] lut_idx_reg_1173;
wire   [6:0] lut_idx_1_fu_527_p3;
reg   [6:0] lut_idx_1_reg_1179;
wire  signed [11:0] abs_dx_1_fu_557_p3;
reg  signed [11:0] abs_dx_1_reg_1194;
wire   [1:0] sel_tmp_fu_574_p3;
reg   [1:0] sel_tmp_reg_1200;
reg   [1:0] sel_tmp_reg_1200_pp0_iter10_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter11_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter12_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter13_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter14_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter15_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter16_reg;
reg   [1:0] sel_tmp_reg_1200_pp0_iter17_reg;
reg   [16:0] kLaserScaleQ16_load_reg_1206;
reg   [16:0] kInfraredScaleQ16_load_reg_1211;
wire   [0:0] icmp_ln141_fu_582_p2;
reg   [0:0] icmp_ln141_reg_1216;
reg   [0:0] icmp_ln141_reg_1216_pp0_iter11_reg;
wire   [24:0] zext_ln154_fu_590_p1;
wire   [16:0] scale_q16_fu_600_p3;
reg   [16:0] scale_q16_reg_1227;
reg   [4:0] tmp_9_reg_1233;
reg   [13:0] tmp_3_reg_1238;
wire   [8:0] trunc_ln158_fu_651_p1;
reg   [8:0] trunc_ln158_reg_1243;
wire   [14:0] raw_delta_fu_687_p2;
reg  signed [14:0] raw_delta_reg_1268;
wire   [8:0] weight_fu_693_p2;
reg   [8:0] weight_reg_1273;
wire   [0:0] or_ln147_1_fu_703_p2;
reg   [0:0] or_ln147_1_reg_1278;
reg   [0:0] or_ln147_1_reg_1278_pp0_iter13_reg;
reg   [0:0] or_ln147_1_reg_1278_pp0_iter14_reg;
reg   [12:0] trunc_ln_reg_1284;
reg   [13:0] trunc_ln82_1_reg_1289;
wire  signed [13:0] src_x_s_fu_743_p2;
reg  signed [13:0] src_x_s_reg_1304;
wire  signed [14:0] src_y_s_unclamped_fu_752_p2;
reg  signed [14:0] src_y_s_unclamped_reg_1310;
wire   [0:0] icmp_ln53_fu_768_p2;
reg   [0:0] icmp_ln53_reg_1316;
wire   [23:0] grp_fu_734_p2;
reg   [23:0] weighted_reg_1321;
reg   [15:0] delta_4_reg_1326;
wire   [0:0] icmp_ln42_fu_794_p2;
reg   [0:0] icmp_ln42_reg_1332;
wire  signed [12:0] base_delta_line_fu_848_p2;
reg  signed [12:0] base_delta_line_reg_1337;
wire   [7:0] trunc_ln211_fu_853_p1;
reg   [7:0] trunc_ln211_reg_1342;
wire  signed [12:0] curve_delta_line_fu_902_p9;
reg  signed [12:0] curve_delta_line_reg_1347;
wire   [7:0] trunc_ln215_fu_922_p1;
reg   [7:0] trunc_ln215_reg_1352;
wire   [10:0] mapped_x_1_fu_964_p9;
reg   [10:0] mapped_x_1_reg_1357;
reg   [10:0] mapped_x_1_reg_1357_pp0_iter16_reg;
reg   [10:0] mapped_x_1_reg_1357_pp0_iter17_reg;
wire   [7:0] add_ln167_fu_988_p2;
reg   [7:0] add_ln167_reg_1362;
wire   [13:0] shift_1_fu_992_p2;
reg   [13:0] shift_1_reg_1367;
wire   [7:0] mapped_slot_fu_1029_p2;
reg   [7:0] mapped_slot_reg_1373;
wire   [63:0] zext_ln200_fu_534_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001;
reg    kLaserScaleQ16_ce0_local;
reg    kInfraredScaleQ16_ce0_local;
wire   [0:0] tmp_1_fu_334_p3;
wire   [11:0] sub_ln34_fu_342_p2;
wire   [0:0] tmp_2_fu_356_p3;
wire   [12:0] sub_ln34_1_fu_364_p2;
wire   [12:0] min_v_fu_400_p3;
wire   [14:0] p_shl_fu_409_p3;
wire   [14:0] zext_ln63_1_fu_405_p1;
wire   [12:0] max_v_fu_423_p3;
wire   [11:0] tmp_fu_432_p4;
wire   [13:0] zext_ln63_2_fu_441_p1;
wire   [13:0] zext_ln63_fu_428_p1;
wire   [0:0] icmp_ln64_fu_455_p2;
wire   [10:0] zext_ln74_fu_467_p1;
wire   [11:0] shl_ln_fu_476_p3;
wire  signed [13:0] sext_ln74_fu_487_p1;
wire   [13:0] zext_ln74_1_fu_483_p1;
wire  signed [14:0] sext_ln74_1_fu_503_p1;
wire   [14:0] shl_ln74_1_fu_496_p3;
wire   [14:0] scaled_fu_506_p2;
wire   [0:0] icmp_ln76_fu_522_p2;
wire   [11:0] dx_1_fu_539_p2;
wire   [0:0] tmp_7_fu_544_p3;
wire   [11:0] abs_dx_fu_552_p2;
wire   [0:0] and_ln190_fu_565_p2;
wire   [0:0] xor_ln222_fu_569_p2;
wire  signed [12:0] sext_ln154_fu_587_p1;
wire   [12:0] grp_fu_594_p0;
wire   [12:0] grp_fu_594_p1;
wire   [12:0] line_delta_fu_605_p2;
wire   [0:0] tmp_8_fu_610_p3;
wire   [12:0] dist_to_line_fu_618_p2;
wire   [12:0] dist_to_line_1_fu_623_p3;
wire   [24:0] grp_fu_594_p2;
wire   [16:0] grp_fu_664_p0;
wire   [16:0] grp_fu_673_p0;
wire   [14:0] zext_ln157_fu_684_p1;
wire   [0:0] icmp_ln147_fu_679_p2;
wire   [0:0] or_ln147_fu_698_p2;
wire   [28:0] grp_fu_664_p2;
wire   [29:0] grp_fu_673_p2;
wire   [8:0] grp_fu_734_p1;
wire  signed [13:0] sext_ln208_fu_740_p1;
wire  signed [14:0] sext_ln209_fu_749_p1;
wire   [3:0] tmp_6_fu_758_p4;
wire   [2:0] tmp_11_fu_784_p4;
wire  signed [15:0] sext_ln209_1_fu_803_p1;
wire   [0:0] tmp_5_fu_806_p3;
wire   [0:0] xor_ln50_fu_817_p2;
wire   [0:0] or_ln50_fu_831_p2;
wire   [10:0] select_ln50_fu_823_p3;
wire   [10:0] trunc_ln56_fu_814_p1;
wire   [10:0] src_y_fu_836_p3;
wire   [12:0] zext_ln211_fu_844_p1;
wire   [0:0] icmp_ln123_fu_862_p2;
wire   [12:0] trunc_ln3_fu_867_p4;
wire   [0:0] icmp_ln120_fu_857_p2;
wire   [0:0] xor_ln147_fu_884_p2;
wire   [0:0] and_ln120_fu_889_p2;
wire   [12:0] curve_delta_line_fu_902_p6;
wire   [12:0] curve_delta_line_fu_902_p7;
wire   [1:0] curve_delta_line_fu_902_p8;
wire  signed [15:0] sext_ln208_1_fu_800_p1;
wire   [0:0] tmp_10_fu_926_p3;
wire   [0:0] xor_ln39_fu_937_p2;
wire   [0:0] or_ln39_fu_951_p2;
wire   [10:0] select_ln39_fu_943_p3;
wire   [10:0] trunc_ln45_fu_934_p1;
wire   [10:0] mapped_x_1_fu_964_p2;
wire   [10:0] mapped_x_1_fu_964_p7;
wire  signed [13:0] sext_ln211_fu_982_p1;
wire  signed [13:0] sext_ln216_fu_985_p1;
wire   [0:0] icmp_ln120_1_fu_998_p2;
wire   [0:0] icmp_ln123_1_fu_1003_p2;
wire   [0:0] or_ln167_fu_1016_p2;
wire   [7:0] select_ln167_fu_1008_p3;
wire   [7:0] select_ln167_1_fu_1022_p3;
wire   [7:0] mapped_slot_1_fu_1034_p7;
wire   [7:0] mapped_slot_1_fu_1034_p9;
wire   [28:0] grp_fu_664_p00;
wire   [29:0] grp_fu_673_p00;
wire   [23:0] grp_fu_734_p10;
wire  signed [1:0] curve_delta_line_fu_902_p1;
wire   [1:0] curve_delta_line_fu_902_p3;
wire   [1:0] curve_delta_line_fu_902_p5;
wire  signed [1:0] mapped_x_1_fu_964_p1;
wire   [1:0] mapped_x_1_fu_964_p3;
wire   [1:0] mapped_x_1_fu_964_p5;
wire  signed [1:0] mapped_slot_1_fu_1034_p1;
wire   [1:0] mapped_slot_1_fu_1034_p3;
wire   [1:0] mapped_slot_1_fu_1034_p5;
wire    ap_ce_reg;

fisheye_remap_addr_hls_kLaserScaleQ16_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 101 ),
    .AddressWidth( 7 ))
kLaserScaleQ16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kLaserScaleQ16_address0),
    .ce0(kLaserScaleQ16_ce0_local),
    .q0(kLaserScaleQ16_q0)
);

fisheye_remap_addr_hls_kInfraredScaleQ16_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 101 ),
    .AddressWidth( 7 ))
kInfraredScaleQ16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kInfraredScaleQ16_address0),
    .ce0(kInfraredScaleQ16_ce0_local),
    .q0(kInfraredScaleQ16_q0)
);

fisheye_remap_addr_hls_mul_13ns_13ns_25_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 25 ))
mul_13ns_13ns_25_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_594_p0),
    .din1(grp_fu_594_p1),
    .ce(1'b1),
    .dout(grp_fu_594_p2)
);

fisheye_remap_addr_hls_mul_17ns_12s_29_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 29 ))
mul_17ns_12s_29_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_664_p0),
    .din1(dx_reg_1090_pp0_iter11_reg),
    .ce(1'b1),
    .dout(grp_fu_664_p2)
);

fisheye_remap_addr_hls_mul_17ns_13s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 30 ))
mul_17ns_13s_30_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_673_p0),
    .din1(dy_reg_1102_pp0_iter11_reg),
    .ce(1'b1),
    .dout(grp_fu_673_p2)
);

fisheye_remap_addr_hls_mul_15s_9ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_15s_9ns_24_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(raw_delta_reg_1268),
    .din1(grp_fu_734_p1),
    .ce(1'b1),
    .dout(grp_fu_734_p2)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_addr_hls_sparsemux_7_2_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 13 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 13 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 13 ),
    .def_WIDTH( 13 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 13 ))
sparsemux_7_2_13_1_1_U5(
    .din0(13'd0),
    .din1(13'd96),
    .din2(curve_delta_line_fu_902_p6),
    .def(curve_delta_line_fu_902_p7),
    .sel(curve_delta_line_fu_902_p8),
    .dout(curve_delta_line_fu_902_p9)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_addr_hls_sparsemux_7_2_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 11 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 11 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 11 ),
    .def_WIDTH( 11 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 11 ))
sparsemux_7_2_11_1_1_U6(
    .din0(mapped_x_1_fu_964_p2),
    .din1(11'd0),
    .din2(out_x_read_reg_1061_pp0_iter14_reg),
    .def(mapped_x_1_fu_964_p7),
    .sel(sel_tmp_reg_1200_pp0_iter14_reg),
    .dout(mapped_x_1_fu_964_p9)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_addr_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U7(
    .din0(mapped_slot_reg_1373),
    .din1(8'd0),
    .din2(out_slot_1_reg_1073_pp0_iter17_reg),
    .def(mapped_slot_1_fu_1034_p7),
    .sel(sel_tmp_reg_1200_pp0_iter17_reg),
    .dout(mapped_slot_1_fu_1034_p9)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        abs_dx_1_reg_1194 <= abs_dx_1_fu_557_p3;
        add_ln167_reg_1362 <= add_ln167_fu_988_p2;
        base_delta_line_reg_1337 <= base_delta_line_fu_848_p2;
        curve_delta_line_reg_1347 <= curve_delta_line_fu_902_p9;
        delta_4_reg_1326 <= {{grp_fu_734_p2[23:8]}};
        delta_reg_1112 <= delta_fu_370_p3;
        delta_reg_1112_pp0_iter1_reg <= delta_reg_1112;
        delta_reg_1112_pp0_iter2_reg <= delta_reg_1112_pp0_iter1_reg;
        dx_reg_1090 <= dx_fu_318_p2;
        dx_reg_1090_pp0_iter10_reg <= dx_reg_1090_pp0_iter9_reg;
        dx_reg_1090_pp0_iter11_reg <= dx_reg_1090_pp0_iter10_reg;
        dx_reg_1090_pp0_iter1_reg <= dx_reg_1090;
        dx_reg_1090_pp0_iter2_reg <= dx_reg_1090_pp0_iter1_reg;
        dx_reg_1090_pp0_iter3_reg <= dx_reg_1090_pp0_iter2_reg;
        dx_reg_1090_pp0_iter4_reg <= dx_reg_1090_pp0_iter3_reg;
        dx_reg_1090_pp0_iter5_reg <= dx_reg_1090_pp0_iter4_reg;
        dx_reg_1090_pp0_iter6_reg <= dx_reg_1090_pp0_iter5_reg;
        dx_reg_1090_pp0_iter7_reg <= dx_reg_1090_pp0_iter6_reg;
        dx_reg_1090_pp0_iter8_reg <= dx_reg_1090_pp0_iter7_reg;
        dx_reg_1090_pp0_iter9_reg <= dx_reg_1090_pp0_iter8_reg;
        dy_reg_1102 <= dy_fu_328_p2;
        dy_reg_1102_pp0_iter10_reg <= dy_reg_1102_pp0_iter9_reg;
        dy_reg_1102_pp0_iter11_reg <= dy_reg_1102_pp0_iter10_reg;
        dy_reg_1102_pp0_iter1_reg <= dy_reg_1102;
        dy_reg_1102_pp0_iter2_reg <= dy_reg_1102_pp0_iter1_reg;
        dy_reg_1102_pp0_iter3_reg <= dy_reg_1102_pp0_iter2_reg;
        dy_reg_1102_pp0_iter4_reg <= dy_reg_1102_pp0_iter3_reg;
        dy_reg_1102_pp0_iter5_reg <= dy_reg_1102_pp0_iter4_reg;
        dy_reg_1102_pp0_iter6_reg <= dy_reg_1102_pp0_iter5_reg;
        dy_reg_1102_pp0_iter7_reg <= dy_reg_1102_pp0_iter6_reg;
        dy_reg_1102_pp0_iter8_reg <= dy_reg_1102_pp0_iter7_reg;
        dy_reg_1102_pp0_iter9_reg <= dy_reg_1102_pp0_iter8_reg;
        icmp_ln135_reg_1124 <= icmp_ln135_fu_386_p2;
        icmp_ln135_reg_1124_pp0_iter10_reg <= icmp_ln135_reg_1124_pp0_iter9_reg;
        icmp_ln135_reg_1124_pp0_iter11_reg <= icmp_ln135_reg_1124_pp0_iter10_reg;
        icmp_ln135_reg_1124_pp0_iter1_reg <= icmp_ln135_reg_1124;
        icmp_ln135_reg_1124_pp0_iter2_reg <= icmp_ln135_reg_1124_pp0_iter1_reg;
        icmp_ln135_reg_1124_pp0_iter3_reg <= icmp_ln135_reg_1124_pp0_iter2_reg;
        icmp_ln135_reg_1124_pp0_iter4_reg <= icmp_ln135_reg_1124_pp0_iter3_reg;
        icmp_ln135_reg_1124_pp0_iter5_reg <= icmp_ln135_reg_1124_pp0_iter4_reg;
        icmp_ln135_reg_1124_pp0_iter6_reg <= icmp_ln135_reg_1124_pp0_iter5_reg;
        icmp_ln135_reg_1124_pp0_iter7_reg <= icmp_ln135_reg_1124_pp0_iter6_reg;
        icmp_ln135_reg_1124_pp0_iter8_reg <= icmp_ln135_reg_1124_pp0_iter7_reg;
        icmp_ln135_reg_1124_pp0_iter9_reg <= icmp_ln135_reg_1124_pp0_iter8_reg;
        icmp_ln141_reg_1216 <= icmp_ln141_fu_582_p2;
        icmp_ln141_reg_1216_pp0_iter11_reg <= icmp_ln141_reg_1216;
        icmp_ln42_reg_1332 <= icmp_ln42_fu_794_p2;
        icmp_ln53_reg_1316 <= icmp_ln53_fu_768_p2;
        icmp_ln61_reg_1135 <= icmp_ln61_fu_395_p2;
        icmp_ln61_reg_1135_pp0_iter2_reg <= icmp_ln61_reg_1135;
        in_valid_read_reg_1066 <= in_valid;
        in_valid_read_reg_1066_pp0_iter10_reg <= in_valid_read_reg_1066_pp0_iter9_reg;
        in_valid_read_reg_1066_pp0_iter11_reg <= in_valid_read_reg_1066_pp0_iter10_reg;
        in_valid_read_reg_1066_pp0_iter12_reg <= in_valid_read_reg_1066_pp0_iter11_reg;
        in_valid_read_reg_1066_pp0_iter13_reg <= in_valid_read_reg_1066_pp0_iter12_reg;
        in_valid_read_reg_1066_pp0_iter14_reg <= in_valid_read_reg_1066_pp0_iter13_reg;
        in_valid_read_reg_1066_pp0_iter15_reg <= in_valid_read_reg_1066_pp0_iter14_reg;
        in_valid_read_reg_1066_pp0_iter16_reg <= in_valid_read_reg_1066_pp0_iter15_reg;
        in_valid_read_reg_1066_pp0_iter17_reg <= in_valid_read_reg_1066_pp0_iter16_reg;
        in_valid_read_reg_1066_pp0_iter1_reg <= in_valid_read_reg_1066;
        in_valid_read_reg_1066_pp0_iter2_reg <= in_valid_read_reg_1066_pp0_iter1_reg;
        in_valid_read_reg_1066_pp0_iter3_reg <= in_valid_read_reg_1066_pp0_iter2_reg;
        in_valid_read_reg_1066_pp0_iter4_reg <= in_valid_read_reg_1066_pp0_iter3_reg;
        in_valid_read_reg_1066_pp0_iter5_reg <= in_valid_read_reg_1066_pp0_iter4_reg;
        in_valid_read_reg_1066_pp0_iter6_reg <= in_valid_read_reg_1066_pp0_iter5_reg;
        in_valid_read_reg_1066_pp0_iter7_reg <= in_valid_read_reg_1066_pp0_iter6_reg;
        in_valid_read_reg_1066_pp0_iter8_reg <= in_valid_read_reg_1066_pp0_iter7_reg;
        in_valid_read_reg_1066_pp0_iter9_reg <= in_valid_read_reg_1066_pp0_iter8_reg;
        kInfraredScaleQ16_load_reg_1211 <= kInfraredScaleQ16_q0;
        kLaserScaleQ16_load_reg_1206 <= kLaserScaleQ16_q0;
        lut_idx_1_reg_1179 <= lut_idx_1_fu_527_p3;
        lut_idx_reg_1173 <= {{scaled_fu_506_p2[14:8]}};
        mapped_slot_reg_1373 <= mapped_slot_fu_1029_p2;
        mapped_x_1_reg_1357 <= mapped_x_1_fu_964_p9;
        mapped_x_1_reg_1357_pp0_iter16_reg <= mapped_x_1_reg_1357;
        mapped_x_1_reg_1357_pp0_iter17_reg <= mapped_x_1_reg_1357_pp0_iter16_reg;
        or_ln147_1_reg_1278 <= or_ln147_1_fu_703_p2;
        or_ln147_1_reg_1278_pp0_iter13_reg <= or_ln147_1_reg_1278;
        or_ln147_1_reg_1278_pp0_iter14_reg <= or_ln147_1_reg_1278_pp0_iter13_reg;
        out_slot_1_reg_1073 <= out_slot_1_fu_306_p1;
        out_slot_1_reg_1073_pp0_iter10_reg <= out_slot_1_reg_1073_pp0_iter9_reg;
        out_slot_1_reg_1073_pp0_iter11_reg <= out_slot_1_reg_1073_pp0_iter10_reg;
        out_slot_1_reg_1073_pp0_iter12_reg <= out_slot_1_reg_1073_pp0_iter11_reg;
        out_slot_1_reg_1073_pp0_iter13_reg <= out_slot_1_reg_1073_pp0_iter12_reg;
        out_slot_1_reg_1073_pp0_iter14_reg <= out_slot_1_reg_1073_pp0_iter13_reg;
        out_slot_1_reg_1073_pp0_iter15_reg <= out_slot_1_reg_1073_pp0_iter14_reg;
        out_slot_1_reg_1073_pp0_iter16_reg <= out_slot_1_reg_1073_pp0_iter15_reg;
        out_slot_1_reg_1073_pp0_iter17_reg <= out_slot_1_reg_1073_pp0_iter16_reg;
        out_slot_1_reg_1073_pp0_iter1_reg <= out_slot_1_reg_1073;
        out_slot_1_reg_1073_pp0_iter2_reg <= out_slot_1_reg_1073_pp0_iter1_reg;
        out_slot_1_reg_1073_pp0_iter3_reg <= out_slot_1_reg_1073_pp0_iter2_reg;
        out_slot_1_reg_1073_pp0_iter4_reg <= out_slot_1_reg_1073_pp0_iter3_reg;
        out_slot_1_reg_1073_pp0_iter5_reg <= out_slot_1_reg_1073_pp0_iter4_reg;
        out_slot_1_reg_1073_pp0_iter6_reg <= out_slot_1_reg_1073_pp0_iter5_reg;
        out_slot_1_reg_1073_pp0_iter7_reg <= out_slot_1_reg_1073_pp0_iter6_reg;
        out_slot_1_reg_1073_pp0_iter8_reg <= out_slot_1_reg_1073_pp0_iter7_reg;
        out_slot_1_reg_1073_pp0_iter9_reg <= out_slot_1_reg_1073_pp0_iter8_reg;
        out_x_read_reg_1061 <= out_x;
        out_x_read_reg_1061_pp0_iter10_reg <= out_x_read_reg_1061_pp0_iter9_reg;
        out_x_read_reg_1061_pp0_iter11_reg <= out_x_read_reg_1061_pp0_iter10_reg;
        out_x_read_reg_1061_pp0_iter12_reg <= out_x_read_reg_1061_pp0_iter11_reg;
        out_x_read_reg_1061_pp0_iter13_reg <= out_x_read_reg_1061_pp0_iter12_reg;
        out_x_read_reg_1061_pp0_iter14_reg <= out_x_read_reg_1061_pp0_iter13_reg;
        out_x_read_reg_1061_pp0_iter1_reg <= out_x_read_reg_1061;
        out_x_read_reg_1061_pp0_iter2_reg <= out_x_read_reg_1061_pp0_iter1_reg;
        out_x_read_reg_1061_pp0_iter3_reg <= out_x_read_reg_1061_pp0_iter2_reg;
        out_x_read_reg_1061_pp0_iter4_reg <= out_x_read_reg_1061_pp0_iter3_reg;
        out_x_read_reg_1061_pp0_iter5_reg <= out_x_read_reg_1061_pp0_iter4_reg;
        out_x_read_reg_1061_pp0_iter6_reg <= out_x_read_reg_1061_pp0_iter5_reg;
        out_x_read_reg_1061_pp0_iter7_reg <= out_x_read_reg_1061_pp0_iter6_reg;
        out_x_read_reg_1061_pp0_iter8_reg <= out_x_read_reg_1061_pp0_iter7_reg;
        out_x_read_reg_1061_pp0_iter9_reg <= out_x_read_reg_1061_pp0_iter8_reg;
        packet_pixel_idx_read_reg_1056 <= packet_pixel_idx;
        packet_pixel_idx_read_reg_1056_pp0_iter10_reg <= packet_pixel_idx_read_reg_1056_pp0_iter9_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter11_reg <= packet_pixel_idx_read_reg_1056_pp0_iter10_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter12_reg <= packet_pixel_idx_read_reg_1056_pp0_iter11_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter13_reg <= packet_pixel_idx_read_reg_1056_pp0_iter12_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter14_reg <= packet_pixel_idx_read_reg_1056_pp0_iter13_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter15_reg <= packet_pixel_idx_read_reg_1056_pp0_iter14_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter16_reg <= packet_pixel_idx_read_reg_1056_pp0_iter15_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter17_reg <= packet_pixel_idx_read_reg_1056_pp0_iter16_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter1_reg <= packet_pixel_idx_read_reg_1056;
        packet_pixel_idx_read_reg_1056_pp0_iter2_reg <= packet_pixel_idx_read_reg_1056_pp0_iter1_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter3_reg <= packet_pixel_idx_read_reg_1056_pp0_iter2_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter4_reg <= packet_pixel_idx_read_reg_1056_pp0_iter3_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter5_reg <= packet_pixel_idx_read_reg_1056_pp0_iter4_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter6_reg <= packet_pixel_idx_read_reg_1056_pp0_iter5_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter7_reg <= packet_pixel_idx_read_reg_1056_pp0_iter6_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter8_reg <= packet_pixel_idx_read_reg_1056_pp0_iter7_reg;
        packet_pixel_idx_read_reg_1056_pp0_iter9_reg <= packet_pixel_idx_read_reg_1056_pp0_iter8_reg;
        radius_1_reg_1151 <= radius_1_fu_451_p1;
        radius_2_reg_1156 <= radius_2_fu_460_p3;
        radius_2_reg_1156_pp0_iter5_reg <= radius_2_reg_1156;
        radius_2_reg_1156_pp0_iter6_reg <= radius_2_reg_1156_pp0_iter5_reg;
        radius_reg_1146 <= radius_fu_445_p2;
        raw_delta_reg_1268 <= raw_delta_fu_687_p2;
        scale_q16_reg_1227 <= scale_q16_fu_600_p3;
        sel_tmp_reg_1200 <= sel_tmp_fu_574_p3;
        sel_tmp_reg_1200_pp0_iter10_reg <= sel_tmp_reg_1200;
        sel_tmp_reg_1200_pp0_iter11_reg <= sel_tmp_reg_1200_pp0_iter10_reg;
        sel_tmp_reg_1200_pp0_iter12_reg <= sel_tmp_reg_1200_pp0_iter11_reg;
        sel_tmp_reg_1200_pp0_iter13_reg <= sel_tmp_reg_1200_pp0_iter12_reg;
        sel_tmp_reg_1200_pp0_iter14_reg <= sel_tmp_reg_1200_pp0_iter13_reg;
        sel_tmp_reg_1200_pp0_iter15_reg <= sel_tmp_reg_1200_pp0_iter14_reg;
        sel_tmp_reg_1200_pp0_iter16_reg <= sel_tmp_reg_1200_pp0_iter15_reg;
        sel_tmp_reg_1200_pp0_iter17_reg <= sel_tmp_reg_1200_pp0_iter16_reg;
        select_ln34_reg_1107 <= select_ln34_fu_348_p3;
        sext_ln32_reg_1129 <= sext_ln32_fu_392_p1;
        sext_ln32_reg_1129_pp0_iter2_reg <= sext_ln32_reg_1129;
        shift_1_reg_1367 <= shift_1_fu_992_p2;
        src_x_s_reg_1304 <= src_x_s_fu_743_p2;
        src_y_s_unclamped_reg_1310 <= src_y_s_unclamped_fu_752_p2;
        sub_ln63_reg_1141 <= sub_ln63_fu_417_p2;
        sub_ln74_1_reg_1168 <= sub_ln74_1_fu_490_p2;
        sub_ln74_reg_1163 <= sub_ln74_fu_470_p2;
        tmp_3_reg_1238 <= {{grp_fu_594_p2[24:11]}};
        tmp_4_reg_1119 <= algo_ctrl[32'd3];
        tmp_4_reg_1119_pp0_iter10_reg <= tmp_4_reg_1119_pp0_iter9_reg;
        tmp_4_reg_1119_pp0_iter1_reg <= tmp_4_reg_1119;
        tmp_4_reg_1119_pp0_iter2_reg <= tmp_4_reg_1119_pp0_iter1_reg;
        tmp_4_reg_1119_pp0_iter3_reg <= tmp_4_reg_1119_pp0_iter2_reg;
        tmp_4_reg_1119_pp0_iter4_reg <= tmp_4_reg_1119_pp0_iter3_reg;
        tmp_4_reg_1119_pp0_iter5_reg <= tmp_4_reg_1119_pp0_iter4_reg;
        tmp_4_reg_1119_pp0_iter6_reg <= tmp_4_reg_1119_pp0_iter5_reg;
        tmp_4_reg_1119_pp0_iter7_reg <= tmp_4_reg_1119_pp0_iter6_reg;
        tmp_4_reg_1119_pp0_iter8_reg <= tmp_4_reg_1119_pp0_iter7_reg;
        tmp_4_reg_1119_pp0_iter9_reg <= tmp_4_reg_1119_pp0_iter8_reg;
        tmp_9_reg_1233 <= {{dist_to_line_1_fu_623_p3[12:8]}};
        trunc_ln158_reg_1243 <= trunc_ln158_fu_651_p1;
        trunc_ln190_reg_1079 <= trunc_ln190_fu_310_p1;
        trunc_ln190_reg_1079_pp0_iter1_reg <= trunc_ln190_reg_1079;
        trunc_ln190_reg_1079_pp0_iter2_reg <= trunc_ln190_reg_1079_pp0_iter1_reg;
        trunc_ln190_reg_1079_pp0_iter3_reg <= trunc_ln190_reg_1079_pp0_iter2_reg;
        trunc_ln190_reg_1079_pp0_iter4_reg <= trunc_ln190_reg_1079_pp0_iter3_reg;
        trunc_ln190_reg_1079_pp0_iter5_reg <= trunc_ln190_reg_1079_pp0_iter4_reg;
        trunc_ln190_reg_1079_pp0_iter6_reg <= trunc_ln190_reg_1079_pp0_iter5_reg;
        trunc_ln190_reg_1079_pp0_iter7_reg <= trunc_ln190_reg_1079_pp0_iter6_reg;
        trunc_ln190_reg_1079_pp0_iter8_reg <= trunc_ln190_reg_1079_pp0_iter7_reg;
        trunc_ln211_reg_1342 <= trunc_ln211_fu_853_p1;
        trunc_ln215_reg_1352 <= trunc_ln215_fu_922_p1;
        trunc_ln82_1_reg_1289 <= {{grp_fu_673_p2[29:16]}};
        trunc_ln_reg_1284 <= {{grp_fu_664_p2[28:16]}};
        weight_reg_1273 <= weight_fu_693_p2;
        weighted_reg_1321 <= grp_fu_734_p2;
        zext_ln196_reg_1084[10 : 0] <= zext_ln196_fu_314_p1[10 : 0];
        zext_ln196_reg_1084_pp0_iter1_reg[10 : 0] <= zext_ln196_reg_1084[10 : 0];
        zext_ln196_reg_1084_pp0_iter2_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter1_reg[10 : 0];
        zext_ln196_reg_1084_pp0_iter3_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter2_reg[10 : 0];
        zext_ln196_reg_1084_pp0_iter4_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter3_reg[10 : 0];
        zext_ln196_reg_1084_pp0_iter5_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter4_reg[10 : 0];
        zext_ln196_reg_1084_pp0_iter6_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter5_reg[10 : 0];
        zext_ln196_reg_1084_pp0_iter7_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter6_reg[10 : 0];
        zext_ln196_reg_1084_pp0_iter8_reg[10 : 0] <= zext_ln196_reg_1084_pp0_iter7_reg[10 : 0];
        zext_ln197_reg_1095[11 : 0] <= zext_ln197_fu_324_p1[11 : 0];
        zext_ln197_reg_1095_pp0_iter10_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter9_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter11_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter10_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter12_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter11_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter13_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter12_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter14_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter13_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter1_reg[11 : 0] <= zext_ln197_reg_1095[11 : 0];
        zext_ln197_reg_1095_pp0_iter2_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter1_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter3_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter2_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter4_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter3_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter5_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter4_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter6_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter5_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter7_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter6_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter8_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter7_reg[11 : 0];
        zext_ln197_reg_1095_pp0_iter9_reg[11 : 0] <= zext_ln197_reg_1095_pp0_iter8_reg[11 : 0];
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        kInfraredScaleQ16_ce0_local = 1'b1;
    end else begin
        kInfraredScaleQ16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        kLaserScaleQ16_ce0_local = 1'b1;
    end else begin
        kLaserScaleQ16_ce0_local = 1'b0;
    end
end

assign abs_dx_1_fu_557_p3 = ((tmp_7_fu_544_p3[0:0] == 1'b1) ? abs_dx_fu_552_p2 : dx_1_fu_539_p2);

assign abs_dx_fu_552_p2 = (12'd964 - zext_ln196_reg_1084_pp0_iter8_reg);

assign add_ln167_fu_988_p2 = (trunc_ln211_reg_1342 + trunc_ln215_reg_1352);

assign and_ln120_fu_889_p2 = (xor_ln147_fu_884_p2 & icmp_ln120_fu_857_p2);

assign and_ln190_fu_565_p2 = (trunc_ln190_reg_1079_pp0_iter8_reg & in_valid_read_reg_1066_pp0_iter8_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign base_delta_line_fu_848_p2 = (zext_ln211_fu_844_p1 - zext_ln197_reg_1095_pp0_iter14_reg);

assign curve_delta_line_fu_902_p6 = ((icmp_ln123_fu_862_p2[0:0] == 1'b1) ? 13'd8096 : trunc_ln3_fu_867_p4);

assign curve_delta_line_fu_902_p7 = 'bx;

assign curve_delta_line_fu_902_p8 = {{or_ln147_1_reg_1278_pp0_iter14_reg}, {and_ln120_fu_889_p2}};

assign delta_fu_370_p3 = ((tmp_2_fu_356_p3[0:0] == 1'b1) ? sub_ln34_1_fu_364_p2 : dy_fu_328_p2);

assign dist_to_line_1_fu_623_p3 = ((tmp_8_fu_610_p3[0:0] == 1'b1) ? dist_to_line_fu_618_p2 : line_delta_fu_605_p2);

assign dist_to_line_fu_618_p2 = (13'd1606 - zext_ln197_reg_1095_pp0_iter10_reg);

assign dx_1_fu_539_p2 = ($signed(zext_ln196_reg_1084_pp0_iter8_reg) + $signed(12'd3132));

assign dx_fu_318_p2 = ($signed(zext_ln196_fu_314_p1) + $signed(12'd3137));

assign dy_fu_328_p2 = ($signed(zext_ln197_fu_324_p1) + $signed(13'd7205));

assign grp_fu_594_p0 = zext_ln154_fu_590_p1;

assign grp_fu_594_p1 = zext_ln154_fu_590_p1;

assign grp_fu_664_p0 = grp_fu_664_p00;

assign grp_fu_664_p00 = scale_q16_reg_1227;

assign grp_fu_673_p0 = grp_fu_673_p00;

assign grp_fu_673_p00 = scale_q16_reg_1227;

assign grp_fu_734_p1 = grp_fu_734_p10;

assign grp_fu_734_p10 = weight_reg_1273;

assign icmp_ln120_1_fu_998_p2 = (($signed(shift_1_reg_1367) > $signed(14'd96)) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_857_p2 = (($signed(delta_4_reg_1326) > $signed(16'd96)) ? 1'b1 : 1'b0);

assign icmp_ln123_1_fu_1003_p2 = (($signed(shift_1_reg_1367) < $signed(14'd16288)) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_862_p2 = (($signed(delta_4_reg_1326) < $signed(16'd65440)) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_386_p2 = ((out_line < 12'd981) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_582_p2 = ((abs_dx_1_reg_1194 > 12'd760) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_679_p2 = ((tmp_9_reg_1233 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_794_p2 = (($signed(tmp_11_fu_784_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_768_p2 = (($signed(tmp_6_fu_758_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_395_p2 = ((sext_ln32_fu_392_p1 > delta_reg_1112) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_455_p2 = ((radius_reg_1146 > 14'd947) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_522_p2 = ((lut_idx_reg_1173 > 7'd100) ? 1'b1 : 1'b0);

assign kInfraredScaleQ16_address0 = zext_ln200_fu_534_p1;

assign kLaserScaleQ16_address0 = zext_ln200_fu_534_p1;

assign line_delta_fu_605_p2 = ($signed(zext_ln197_reg_1095_pp0_iter10_reg) + $signed(13'd6586));

assign lut_idx_1_fu_527_p3 = ((icmp_ln76_fu_522_p2[0:0] == 1'b1) ? 7'd100 : lut_idx_reg_1173);

assign mapped_slot_1_fu_1034_p7 = 'bx;

assign mapped_slot_fu_1029_p2 = (select_ln167_1_fu_1022_p3 + out_slot_1_reg_1073_pp0_iter16_reg);

assign mapped_x_1_fu_964_p2 = ((or_ln39_fu_951_p2[0:0] == 1'b1) ? select_ln39_fu_943_p3 : trunc_ln45_fu_934_p1);

assign mapped_x_1_fu_964_p7 = 'bx;

assign max_v_fu_423_p3 = ((icmp_ln61_reg_1135_pp0_iter2_reg[0:0] == 1'b1) ? sext_ln32_reg_1129_pp0_iter2_reg : delta_reg_1112_pp0_iter2_reg);

assign min_v_fu_400_p3 = ((icmp_ln61_reg_1135[0:0] == 1'b1) ? delta_reg_1112_pp0_iter1_reg : sext_ln32_reg_1129);

assign or_ln147_1_fu_703_p2 = (or_ln147_fu_698_p2 | icmp_ln135_reg_1124_pp0_iter11_reg);

assign or_ln147_fu_698_p2 = (icmp_ln147_fu_679_p2 | icmp_ln141_reg_1216_pp0_iter11_reg);

assign or_ln167_fu_1016_p2 = (icmp_ln123_1_fu_1003_p2 | icmp_ln120_1_fu_998_p2);

assign or_ln39_fu_951_p2 = (tmp_10_fu_926_p3 | icmp_ln42_reg_1332);

assign or_ln50_fu_831_p2 = (tmp_5_fu_806_p3 | icmp_ln53_reg_1316);

assign out_slot_1_fu_306_p1 = out_slot[7:0];

assign out_valid = in_valid_read_reg_1066_pp0_iter17_reg;

assign p_shl_fu_409_p3 = {{min_v_fu_400_p3}, {2'd0}};

assign packet_pixel_idx_out = packet_pixel_idx_read_reg_1056_pp0_iter17_reg;

assign radius_1_fu_451_p1 = radius_fu_445_p2[9:0];

assign radius_2_fu_460_p3 = ((icmp_ln64_fu_455_p2[0:0] == 1'b1) ? 10'd947 : radius_1_reg_1151);

assign radius_fu_445_p2 = (zext_ln63_2_fu_441_p1 + zext_ln63_fu_428_p1);

assign raw_delta_fu_687_p2 = (15'd135 - zext_ln157_fu_684_p1);

assign scale_q16_fu_600_p3 = ((tmp_4_reg_1119_pp0_iter10_reg[0:0] == 1'b1) ? kLaserScaleQ16_load_reg_1206 : kInfraredScaleQ16_load_reg_1211);

assign scaled_fu_506_p2 = ($signed(sext_ln74_1_fu_503_p1) + $signed(shl_ln74_1_fu_496_p3));

assign sel_tmp_fu_574_p3 = {{and_ln190_fu_565_p2}, {xor_ln222_fu_569_p2}};

assign select_ln167_1_fu_1022_p3 = ((or_ln167_fu_1016_p2[0:0] == 1'b1) ? select_ln167_fu_1008_p3 : add_ln167_reg_1362);

assign select_ln167_fu_1008_p3 = ((icmp_ln120_1_fu_998_p2[0:0] == 1'b1) ? 8'd96 : 8'd160);

assign select_ln34_fu_348_p3 = ((tmp_1_fu_334_p3[0:0] == 1'b1) ? sub_ln34_fu_342_p2 : dx_fu_318_p2);

assign select_ln39_fu_943_p3 = ((xor_ln39_fu_937_p2[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign select_ln50_fu_823_p3 = ((xor_ln50_fu_817_p2[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign sext_ln154_fu_587_p1 = abs_dx_1_reg_1194;

assign sext_ln208_1_fu_800_p1 = src_x_s_reg_1304;

assign sext_ln208_fu_740_p1 = $signed(trunc_ln_reg_1284);

assign sext_ln209_1_fu_803_p1 = src_y_s_unclamped_reg_1310;

assign sext_ln209_fu_749_p1 = $signed(trunc_ln82_1_reg_1289);

assign sext_ln211_fu_982_p1 = base_delta_line_reg_1337;

assign sext_ln216_fu_985_p1 = curve_delta_line_reg_1347;

assign sext_ln32_fu_392_p1 = $signed(select_ln34_reg_1107);

assign sext_ln74_1_fu_503_p1 = $signed(sub_ln74_1_reg_1168);

assign sext_ln74_fu_487_p1 = $signed(sub_ln74_reg_1163);

assign shift_1_fu_992_p2 = ($signed(sext_ln211_fu_982_p1) + $signed(sext_ln216_fu_985_p1));

assign shl_ln74_1_fu_496_p3 = {{radius_2_reg_1156_pp0_iter6_reg}, {5'd0}};

assign shl_ln_fu_476_p3 = {{radius_2_reg_1156_pp0_iter5_reg}, {2'd0}};

assign src_slot = mapped_slot_1_fu_1034_p9;

assign src_x = mapped_x_1_reg_1357_pp0_iter17_reg;

assign src_x_s_fu_743_p2 = ($signed(sext_ln208_fu_740_p1) + $signed(14'd959));

assign src_y_fu_836_p3 = ((or_ln50_fu_831_p2[0:0] == 1'b1) ? select_ln50_fu_823_p3 : trunc_ln56_fu_814_p1);

assign src_y_s_unclamped_fu_752_p2 = ($signed(sext_ln209_fu_749_p1) + $signed(15'd987));

assign sub_ln34_1_fu_364_p2 = (13'd987 - zext_ln197_fu_324_p1);

assign sub_ln34_fu_342_p2 = (12'd959 - zext_ln196_fu_314_p1);

assign sub_ln63_fu_417_p2 = (p_shl_fu_409_p3 - zext_ln63_1_fu_405_p1);

assign sub_ln74_1_fu_490_p2 = ($signed(sext_ln74_fu_487_p1) - $signed(zext_ln74_1_fu_483_p1));

assign sub_ln74_fu_470_p2 = (11'd128 - zext_ln74_fu_467_p1);

assign tmp_10_fu_926_p3 = sext_ln208_1_fu_800_p1[32'd15];

assign tmp_11_fu_784_p4 = {{src_x_s_fu_743_p2[13:11]}};

assign tmp_1_fu_334_p3 = dx_fu_318_p2[32'd11];

assign tmp_2_fu_356_p3 = dy_fu_328_p2[32'd12];

assign tmp_5_fu_806_p3 = sext_ln209_1_fu_803_p1[32'd15];

assign tmp_6_fu_758_p4 = {{src_y_s_unclamped_fu_752_p2[14:11]}};

assign tmp_7_fu_544_p3 = dx_1_fu_539_p2[32'd11];

assign tmp_8_fu_610_p3 = line_delta_fu_605_p2[32'd12];

assign tmp_fu_432_p4 = {{sub_ln63_reg_1141[14:3]}};

assign trunc_ln158_fu_651_p1 = dist_to_line_1_fu_623_p3[8:0];

assign trunc_ln190_fu_310_p1 = algo_ctrl[0:0];

assign trunc_ln211_fu_853_p1 = base_delta_line_fu_848_p2[7:0];

assign trunc_ln215_fu_922_p1 = curve_delta_line_fu_902_p9[7:0];

assign trunc_ln3_fu_867_p4 = {{weighted_reg_1321[20:8]}};

assign trunc_ln45_fu_934_p1 = src_x_s_reg_1304[10:0];

assign trunc_ln56_fu_814_p1 = src_y_s_unclamped_reg_1310[10:0];

assign weight_fu_693_p2 = ($signed(9'd256) - $signed(trunc_ln158_reg_1243));

assign xor_ln147_fu_884_p2 = (or_ln147_1_reg_1278_pp0_iter14_reg ^ 1'd1);

assign xor_ln222_fu_569_p2 = (in_valid_read_reg_1066_pp0_iter8_reg ^ 1'd1);

assign xor_ln39_fu_937_p2 = (tmp_10_fu_926_p3 ^ 1'd1);

assign xor_ln50_fu_817_p2 = (tmp_5_fu_806_p3 ^ 1'd1);

assign zext_ln154_fu_590_p1 = $unsigned(sext_ln154_fu_587_p1);

assign zext_ln157_fu_684_p1 = tmp_3_reg_1238;

assign zext_ln196_fu_314_p1 = out_x;

assign zext_ln197_fu_324_p1 = out_line;

assign zext_ln200_fu_534_p1 = lut_idx_1_reg_1179;

assign zext_ln211_fu_844_p1 = src_y_fu_836_p3;

assign zext_ln63_1_fu_405_p1 = min_v_fu_400_p3;

assign zext_ln63_2_fu_441_p1 = tmp_fu_432_p4;

assign zext_ln63_fu_428_p1 = max_v_fu_423_p3;

assign zext_ln74_1_fu_483_p1 = shl_ln_fu_476_p3;

assign zext_ln74_fu_467_p1 = radius_2_reg_1156;

always @ (posedge ap_clk) begin
    zext_ln196_reg_1084[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter1_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter2_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter3_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter4_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter5_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter6_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter7_reg[11] <= 1'b0;
    zext_ln196_reg_1084_pp0_iter8_reg[11] <= 1'b0;
    zext_ln197_reg_1095[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter1_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter2_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter3_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter4_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter5_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter6_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter7_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter8_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter9_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter10_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter11_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter12_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter13_reg[12] <= 1'b0;
    zext_ln197_reg_1095_pp0_iter14_reg[12] <= 1'b0;
end

endmodule //fisheye_remap_addr_hls
