// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* CORE_GENERATION_INFO="fisheye_remap_addr_hls_fisheye_remap_addr_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100-ffg900-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.843000,HLS_SYN_LAT=19,HLS_SYN_TPT=1,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1823,HLS_SYN_LUT=1173,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module fisheye_remap_addr_hls (
        ap_clk,
        ap_rst,
        in_valid,
        out_x,
        out_line,
        out_slot,
        packet_pixel_idx,
        algo_ctrl,
        out_valid,
        src_slot,
        src_x,
        packet_pixel_idx_out
);


input   ap_clk;
input   ap_rst;
input  [0:0] in_valid;
input  [10:0] out_x;
input  [11:0] out_line;
input  [8:0] out_slot;
input  [6:0] packet_pixel_idx;
input  [31:0] algo_ctrl;
output  [0:0] out_valid;
output  [8:0] src_slot;
output  [10:0] src_x;
output  [6:0] packet_pixel_idx_out;

wire   [6:0] kLaserScaleQ16_address0;
wire   [16:0] kLaserScaleQ16_q0;
wire   [6:0] kInfraredScaleQ16_address0;
wire   [16:0] kInfraredScaleQ16_q0;
reg   [6:0] packet_pixel_idx_read_reg_1119;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter1_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter2_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter3_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter4_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter5_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter6_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter7_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter8_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter9_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter10_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter11_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter12_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter13_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter14_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter15_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter16_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter17_reg;
reg   [6:0] packet_pixel_idx_read_reg_1119_pp0_iter18_reg;
reg   [10:0] out_x_read_reg_1124;
reg   [10:0] out_x_read_reg_1124_pp0_iter1_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter2_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter3_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter4_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter5_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter6_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter7_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter8_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter9_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter10_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter11_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter12_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter13_reg;
reg   [10:0] out_x_read_reg_1124_pp0_iter14_reg;
reg   [0:0] in_valid_read_reg_1129;
reg   [0:0] in_valid_read_reg_1129_pp0_iter1_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter2_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter3_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter4_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter5_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter6_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter7_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter8_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter9_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter10_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter11_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter12_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter13_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter14_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter15_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter16_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter17_reg;
reg   [0:0] in_valid_read_reg_1129_pp0_iter18_reg;
wire   [7:0] out_slot_1_fu_316_p1;
reg   [7:0] out_slot_1_reg_1136;
reg   [7:0] out_slot_1_reg_1136_pp0_iter1_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter2_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter3_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter4_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter5_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter6_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter7_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter8_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter9_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter10_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter11_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter12_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter13_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter14_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter15_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter16_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter17_reg;
reg   [7:0] out_slot_1_reg_1136_pp0_iter18_reg;
wire   [0:0] trunc_ln190_fu_320_p1;
reg   [0:0] trunc_ln190_reg_1142;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter1_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter2_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter3_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter4_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter5_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter6_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter7_reg;
reg   [0:0] trunc_ln190_reg_1142_pp0_iter8_reg;
wire   [11:0] zext_ln196_fu_324_p1;
reg   [11:0] zext_ln196_reg_1147;
reg   [11:0] zext_ln196_reg_1147_pp0_iter1_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter2_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter3_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter4_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter5_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter6_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter7_reg;
reg   [11:0] zext_ln196_reg_1147_pp0_iter8_reg;
wire  signed [11:0] dx_fu_328_p2;
reg  signed [11:0] dx_reg_1153;
reg  signed [11:0] dx_reg_1153_pp0_iter1_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter2_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter3_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter4_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter5_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter6_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter7_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter8_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter9_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter10_reg;
reg  signed [11:0] dx_reg_1153_pp0_iter11_reg;
wire   [12:0] zext_ln197_fu_334_p1;
reg   [12:0] zext_ln197_reg_1158;
reg   [12:0] zext_ln197_reg_1158_pp0_iter1_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter2_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter3_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter4_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter5_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter6_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter7_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter8_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter9_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter10_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter11_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter12_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter13_reg;
reg   [12:0] zext_ln197_reg_1158_pp0_iter14_reg;
wire  signed [12:0] dy_fu_338_p2;
reg  signed [12:0] dy_reg_1165;
reg  signed [12:0] dy_reg_1165_pp0_iter1_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter2_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter3_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter4_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter5_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter6_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter7_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter8_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter9_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter10_reg;
reg  signed [12:0] dy_reg_1165_pp0_iter11_reg;
wire   [11:0] select_ln34_fu_358_p3;
reg   [11:0] select_ln34_reg_1170;
wire   [12:0] delta_fu_380_p3;
reg   [12:0] delta_reg_1175;
reg   [12:0] delta_reg_1175_pp0_iter1_reg;
reg   [12:0] delta_reg_1175_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_1182;
reg   [0:0] tmp_4_reg_1182_pp0_iter1_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter6_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter7_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter8_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter9_reg;
reg   [0:0] tmp_4_reg_1182_pp0_iter10_reg;
wire   [0:0] icmp_ln135_fu_396_p2;
reg   [0:0] icmp_ln135_reg_1187;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter2_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter3_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter4_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter5_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter6_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter7_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter8_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter9_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter10_reg;
reg   [0:0] icmp_ln135_reg_1187_pp0_iter11_reg;
wire  signed [12:0] sext_ln32_fu_402_p1;
reg  signed [12:0] sext_ln32_reg_1192;
reg  signed [12:0] sext_ln32_reg_1192_pp0_iter2_reg;
wire   [0:0] icmp_ln61_fu_405_p2;
reg   [0:0] icmp_ln61_reg_1198;
reg   [0:0] icmp_ln61_reg_1198_pp0_iter2_reg;
wire   [14:0] sub_ln63_fu_427_p2;
reg   [14:0] sub_ln63_reg_1204;
wire   [13:0] radius_fu_455_p2;
reg   [13:0] radius_reg_1209;
wire   [9:0] radius_1_fu_461_p1;
reg   [9:0] radius_1_reg_1214;
wire   [9:0] radius_2_fu_470_p3;
reg   [9:0] radius_2_reg_1219;
reg   [9:0] radius_2_reg_1219_pp0_iter5_reg;
reg   [9:0] radius_2_reg_1219_pp0_iter6_reg;
wire   [10:0] sub_ln74_fu_480_p2;
reg   [10:0] sub_ln74_reg_1226;
wire   [13:0] sub_ln74_1_fu_500_p2;
reg   [13:0] sub_ln74_1_reg_1231;
reg   [6:0] lut_idx_reg_1236;
wire   [6:0] lut_idx_1_fu_537_p3;
reg   [6:0] lut_idx_1_reg_1242;
wire  signed [11:0] abs_dx_1_fu_567_p3;
reg  signed [11:0] abs_dx_1_reg_1257;
wire   [1:0] sel_tmp_fu_584_p3;
reg   [1:0] sel_tmp_reg_1263;
reg   [1:0] sel_tmp_reg_1263_pp0_iter10_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter11_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter12_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter13_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter14_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter15_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter16_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter17_reg;
reg   [1:0] sel_tmp_reg_1263_pp0_iter18_reg;
reg   [16:0] kLaserScaleQ16_load_reg_1269;
reg   [16:0] kInfraredScaleQ16_load_reg_1274;
wire   [0:0] icmp_ln141_fu_592_p2;
reg   [0:0] icmp_ln141_reg_1279;
reg   [0:0] icmp_ln141_reg_1279_pp0_iter11_reg;
wire   [24:0] zext_ln154_fu_600_p1;
wire   [16:0] scale_q16_fu_610_p3;
reg   [16:0] scale_q16_reg_1290;
reg   [4:0] tmp_9_reg_1296;
reg   [13:0] tmp_3_reg_1301;
wire   [8:0] trunc_ln158_fu_661_p1;
reg   [8:0] trunc_ln158_reg_1306;
wire   [14:0] raw_delta_fu_697_p2;
reg  signed [14:0] raw_delta_reg_1331;
wire   [8:0] weight_fu_703_p2;
reg   [8:0] weight_reg_1336;
wire   [0:0] or_ln147_1_fu_713_p2;
reg   [0:0] or_ln147_1_reg_1341;
reg   [0:0] or_ln147_1_reg_1341_pp0_iter13_reg;
reg   [0:0] or_ln147_1_reg_1341_pp0_iter14_reg;
reg   [12:0] trunc_ln_reg_1347;
reg   [13:0] trunc_ln82_1_reg_1352;
wire  signed [13:0] src_x_s_fu_753_p2;
reg  signed [13:0] src_x_s_reg_1367;
wire  signed [14:0] src_y_s_unclamped_fu_762_p2;
reg  signed [14:0] src_y_s_unclamped_reg_1373;
wire   [0:0] icmp_ln53_fu_778_p2;
reg   [0:0] icmp_ln53_reg_1379;
wire   [23:0] grp_fu_744_p2;
reg   [23:0] weighted_reg_1384;
reg   [15:0] delta_4_reg_1389;
wire   [0:0] icmp_ln42_fu_804_p2;
reg   [0:0] icmp_ln42_reg_1395;
wire  signed [12:0] base_delta_line_fu_858_p2;
reg  signed [12:0] base_delta_line_reg_1400;
wire   [7:0] trunc_ln211_fu_863_p1;
reg   [7:0] trunc_ln211_reg_1405;
wire  signed [12:0] curve_delta_line_fu_912_p9;
reg  signed [12:0] curve_delta_line_reg_1410;
wire   [7:0] trunc_ln215_fu_932_p1;
reg   [7:0] trunc_ln215_reg_1415;
wire   [10:0] mapped_x_1_fu_974_p9;
reg   [10:0] mapped_x_1_reg_1420;
reg   [10:0] mapped_x_1_reg_1420_pp0_iter16_reg;
reg   [10:0] mapped_x_1_reg_1420_pp0_iter17_reg;
reg   [10:0] mapped_x_1_reg_1420_pp0_iter18_reg;
wire   [7:0] add_ln126_fu_998_p2;
reg   [7:0] add_ln126_reg_1425;
wire   [13:0] shift_1_fu_1002_p2;
reg   [13:0] shift_1_reg_1430;
wire   [8:0] trunc_ln167_fu_1052_p1;
reg   [8:0] trunc_ln167_reg_1436;
reg   [0:0] tmp_12_reg_1442;
wire   [8:0] slot_2_fu_1069_p3;
reg   [8:0] slot_2_reg_1447;
wire   [7:0] trunc_ln175_fu_1075_p1;
reg   [7:0] trunc_ln175_reg_1452;
wire   [63:0] zext_ln200_fu_544_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001;
reg    kLaserScaleQ16_ce0_local;
reg    kInfraredScaleQ16_ce0_local;
wire   [0:0] tmp_1_fu_344_p3;
wire   [11:0] sub_ln34_fu_352_p2;
wire   [0:0] tmp_2_fu_366_p3;
wire   [12:0] sub_ln34_1_fu_374_p2;
wire   [12:0] min_v_fu_410_p3;
wire   [14:0] p_shl_fu_419_p3;
wire   [14:0] zext_ln63_1_fu_415_p1;
wire   [12:0] max_v_fu_433_p3;
wire   [11:0] tmp_fu_442_p4;
wire   [13:0] zext_ln63_2_fu_451_p1;
wire   [13:0] zext_ln63_fu_438_p1;
wire   [0:0] icmp_ln64_fu_465_p2;
wire   [10:0] zext_ln74_fu_477_p1;
wire   [11:0] shl_ln_fu_486_p3;
wire  signed [13:0] sext_ln74_fu_497_p1;
wire   [13:0] zext_ln74_1_fu_493_p1;
wire  signed [14:0] sext_ln74_1_fu_513_p1;
wire   [14:0] shl_ln74_1_fu_506_p3;
wire   [14:0] scaled_fu_516_p2;
wire   [0:0] icmp_ln76_fu_532_p2;
wire   [11:0] dx_1_fu_549_p2;
wire   [0:0] tmp_7_fu_554_p3;
wire   [11:0] abs_dx_fu_562_p2;
wire   [0:0] and_ln190_fu_575_p2;
wire   [0:0] xor_ln222_fu_579_p2;
wire  signed [12:0] sext_ln154_fu_597_p1;
wire   [12:0] grp_fu_604_p0;
wire   [12:0] grp_fu_604_p1;
wire   [12:0] line_delta_fu_615_p2;
wire   [0:0] tmp_8_fu_620_p3;
wire   [12:0] dist_to_line_fu_628_p2;
wire   [12:0] dist_to_line_1_fu_633_p3;
wire   [24:0] grp_fu_604_p2;
wire   [16:0] grp_fu_674_p0;
wire   [16:0] grp_fu_683_p0;
wire   [14:0] zext_ln157_fu_694_p1;
wire   [0:0] icmp_ln147_fu_689_p2;
wire   [0:0] or_ln147_fu_708_p2;
wire   [28:0] grp_fu_674_p2;
wire   [29:0] grp_fu_683_p2;
wire   [8:0] grp_fu_744_p1;
wire  signed [13:0] sext_ln208_fu_750_p1;
wire  signed [14:0] sext_ln209_fu_759_p1;
wire   [3:0] tmp_6_fu_768_p4;
wire   [2:0] tmp_11_fu_794_p4;
wire  signed [15:0] sext_ln209_1_fu_813_p1;
wire   [0:0] tmp_5_fu_816_p3;
wire   [0:0] xor_ln50_fu_827_p2;
wire   [0:0] or_ln50_fu_841_p2;
wire   [10:0] select_ln50_fu_833_p3;
wire   [10:0] trunc_ln56_fu_824_p1;
wire   [10:0] src_y_fu_846_p3;
wire   [12:0] zext_ln211_fu_854_p1;
wire   [0:0] icmp_ln123_fu_872_p2;
wire   [12:0] trunc_ln3_fu_877_p4;
wire   [0:0] icmp_ln120_fu_867_p2;
wire   [0:0] xor_ln147_fu_894_p2;
wire   [0:0] and_ln120_fu_899_p2;
wire   [12:0] curve_delta_line_fu_912_p6;
wire   [12:0] curve_delta_line_fu_912_p7;
wire   [1:0] curve_delta_line_fu_912_p8;
wire  signed [15:0] sext_ln208_1_fu_810_p1;
wire   [0:0] tmp_10_fu_936_p3;
wire   [0:0] xor_ln39_fu_947_p2;
wire   [0:0] or_ln39_fu_961_p2;
wire   [10:0] select_ln39_fu_953_p3;
wire   [10:0] trunc_ln45_fu_944_p1;
wire   [10:0] mapped_x_1_fu_974_p2;
wire   [10:0] mapped_x_1_fu_974_p7;
wire  signed [13:0] sext_ln211_fu_992_p1;
wire  signed [13:0] sext_ln216_fu_995_p1;
wire   [0:0] icmp_ln120_1_fu_1008_p2;
wire   [0:0] icmp_ln123_1_fu_1013_p2;
wire   [0:0] or_ln120_fu_1026_p2;
wire   [7:0] select_ln120_fu_1018_p3;
wire   [7:0] safe_delta_line_fu_1032_p3;
wire  signed [9:0] sext_ln167_fu_1039_p1;
wire   [9:0] zext_ln167_fu_1043_p1;
wire   [9:0] slot_fu_1046_p2;
wire   [8:0] slot_1_fu_1064_p2;
wire   [0:0] icmp_ln174_fu_1079_p2;
wire   [7:0] add_ln174_fu_1084_p2;
wire   [7:0] mapped_slot_1_fu_1096_p2;
wire   [7:0] mapped_slot_1_fu_1096_p7;
wire   [7:0] mapped_slot_1_fu_1096_p9;
wire   [28:0] grp_fu_674_p00;
wire   [29:0] grp_fu_683_p00;
wire   [23:0] grp_fu_744_p10;
wire  signed [1:0] curve_delta_line_fu_912_p1;
wire   [1:0] curve_delta_line_fu_912_p3;
wire   [1:0] curve_delta_line_fu_912_p5;
wire  signed [1:0] mapped_x_1_fu_974_p1;
wire   [1:0] mapped_x_1_fu_974_p3;
wire   [1:0] mapped_x_1_fu_974_p5;
wire  signed [1:0] mapped_slot_1_fu_1096_p1;
wire   [1:0] mapped_slot_1_fu_1096_p3;
wire   [1:0] mapped_slot_1_fu_1096_p5;
wire    ap_ce_reg;

fisheye_remap_addr_hls_kLaserScaleQ16_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 101 ),
    .AddressWidth( 7 ))
kLaserScaleQ16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kLaserScaleQ16_address0),
    .ce0(kLaserScaleQ16_ce0_local),
    .q0(kLaserScaleQ16_q0)
);

fisheye_remap_addr_hls_kInfraredScaleQ16_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 101 ),
    .AddressWidth( 7 ))
kInfraredScaleQ16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kInfraredScaleQ16_address0),
    .ce0(kInfraredScaleQ16_ce0_local),
    .q0(kInfraredScaleQ16_q0)
);

fisheye_remap_addr_hls_mul_13ns_13ns_25_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 25 ))
mul_13ns_13ns_25_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_604_p0),
    .din1(grp_fu_604_p1),
    .ce(1'b1),
    .dout(grp_fu_604_p2)
);

fisheye_remap_addr_hls_mul_17ns_12s_29_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 29 ))
mul_17ns_12s_29_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_674_p0),
    .din1(dx_reg_1153_pp0_iter11_reg),
    .ce(1'b1),
    .dout(grp_fu_674_p2)
);

fisheye_remap_addr_hls_mul_17ns_13s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 30 ))
mul_17ns_13s_30_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_683_p0),
    .din1(dy_reg_1165_pp0_iter11_reg),
    .ce(1'b1),
    .dout(grp_fu_683_p2)
);

fisheye_remap_addr_hls_mul_15s_9ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_15s_9ns_24_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(raw_delta_reg_1331),
    .din1(grp_fu_744_p1),
    .ce(1'b1),
    .dout(grp_fu_744_p2)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_addr_hls_sparsemux_7_2_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 13 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 13 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 13 ),
    .def_WIDTH( 13 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 13 ))
sparsemux_7_2_13_1_1_U5(
    .din0(13'd0),
    .din1(13'd96),
    .din2(curve_delta_line_fu_912_p6),
    .def(curve_delta_line_fu_912_p7),
    .sel(curve_delta_line_fu_912_p8),
    .dout(curve_delta_line_fu_912_p9)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_addr_hls_sparsemux_7_2_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 11 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 11 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 11 ),
    .def_WIDTH( 11 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 11 ))
sparsemux_7_2_11_1_1_U6(
    .din0(mapped_x_1_fu_974_p2),
    .din1(11'd0),
    .din2(out_x_read_reg_1124_pp0_iter14_reg),
    .def(mapped_x_1_fu_974_p7),
    .sel(sel_tmp_reg_1263_pp0_iter14_reg),
    .dout(mapped_x_1_fu_974_p9)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_addr_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U7(
    .din0(mapped_slot_1_fu_1096_p2),
    .din1(8'd0),
    .din2(out_slot_1_reg_1136_pp0_iter18_reg),
    .def(mapped_slot_1_fu_1096_p7),
    .sel(sel_tmp_reg_1263_pp0_iter18_reg),
    .dout(mapped_slot_1_fu_1096_p9)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        abs_dx_1_reg_1257 <= abs_dx_1_fu_567_p3;
        add_ln126_reg_1425 <= add_ln126_fu_998_p2;
        base_delta_line_reg_1400 <= base_delta_line_fu_858_p2;
        curve_delta_line_reg_1410 <= curve_delta_line_fu_912_p9;
        delta_4_reg_1389 <= {{grp_fu_744_p2[23:8]}};
        delta_reg_1175 <= delta_fu_380_p3;
        delta_reg_1175_pp0_iter1_reg <= delta_reg_1175;
        delta_reg_1175_pp0_iter2_reg <= delta_reg_1175_pp0_iter1_reg;
        dx_reg_1153 <= dx_fu_328_p2;
        dx_reg_1153_pp0_iter10_reg <= dx_reg_1153_pp0_iter9_reg;
        dx_reg_1153_pp0_iter11_reg <= dx_reg_1153_pp0_iter10_reg;
        dx_reg_1153_pp0_iter1_reg <= dx_reg_1153;
        dx_reg_1153_pp0_iter2_reg <= dx_reg_1153_pp0_iter1_reg;
        dx_reg_1153_pp0_iter3_reg <= dx_reg_1153_pp0_iter2_reg;
        dx_reg_1153_pp0_iter4_reg <= dx_reg_1153_pp0_iter3_reg;
        dx_reg_1153_pp0_iter5_reg <= dx_reg_1153_pp0_iter4_reg;
        dx_reg_1153_pp0_iter6_reg <= dx_reg_1153_pp0_iter5_reg;
        dx_reg_1153_pp0_iter7_reg <= dx_reg_1153_pp0_iter6_reg;
        dx_reg_1153_pp0_iter8_reg <= dx_reg_1153_pp0_iter7_reg;
        dx_reg_1153_pp0_iter9_reg <= dx_reg_1153_pp0_iter8_reg;
        dy_reg_1165 <= dy_fu_338_p2;
        dy_reg_1165_pp0_iter10_reg <= dy_reg_1165_pp0_iter9_reg;
        dy_reg_1165_pp0_iter11_reg <= dy_reg_1165_pp0_iter10_reg;
        dy_reg_1165_pp0_iter1_reg <= dy_reg_1165;
        dy_reg_1165_pp0_iter2_reg <= dy_reg_1165_pp0_iter1_reg;
        dy_reg_1165_pp0_iter3_reg <= dy_reg_1165_pp0_iter2_reg;
        dy_reg_1165_pp0_iter4_reg <= dy_reg_1165_pp0_iter3_reg;
        dy_reg_1165_pp0_iter5_reg <= dy_reg_1165_pp0_iter4_reg;
        dy_reg_1165_pp0_iter6_reg <= dy_reg_1165_pp0_iter5_reg;
        dy_reg_1165_pp0_iter7_reg <= dy_reg_1165_pp0_iter6_reg;
        dy_reg_1165_pp0_iter8_reg <= dy_reg_1165_pp0_iter7_reg;
        dy_reg_1165_pp0_iter9_reg <= dy_reg_1165_pp0_iter8_reg;
        icmp_ln135_reg_1187 <= icmp_ln135_fu_396_p2;
        icmp_ln135_reg_1187_pp0_iter10_reg <= icmp_ln135_reg_1187_pp0_iter9_reg;
        icmp_ln135_reg_1187_pp0_iter11_reg <= icmp_ln135_reg_1187_pp0_iter10_reg;
        icmp_ln135_reg_1187_pp0_iter1_reg <= icmp_ln135_reg_1187;
        icmp_ln135_reg_1187_pp0_iter2_reg <= icmp_ln135_reg_1187_pp0_iter1_reg;
        icmp_ln135_reg_1187_pp0_iter3_reg <= icmp_ln135_reg_1187_pp0_iter2_reg;
        icmp_ln135_reg_1187_pp0_iter4_reg <= icmp_ln135_reg_1187_pp0_iter3_reg;
        icmp_ln135_reg_1187_pp0_iter5_reg <= icmp_ln135_reg_1187_pp0_iter4_reg;
        icmp_ln135_reg_1187_pp0_iter6_reg <= icmp_ln135_reg_1187_pp0_iter5_reg;
        icmp_ln135_reg_1187_pp0_iter7_reg <= icmp_ln135_reg_1187_pp0_iter6_reg;
        icmp_ln135_reg_1187_pp0_iter8_reg <= icmp_ln135_reg_1187_pp0_iter7_reg;
        icmp_ln135_reg_1187_pp0_iter9_reg <= icmp_ln135_reg_1187_pp0_iter8_reg;
        icmp_ln141_reg_1279 <= icmp_ln141_fu_592_p2;
        icmp_ln141_reg_1279_pp0_iter11_reg <= icmp_ln141_reg_1279;
        icmp_ln42_reg_1395 <= icmp_ln42_fu_804_p2;
        icmp_ln53_reg_1379 <= icmp_ln53_fu_778_p2;
        icmp_ln61_reg_1198 <= icmp_ln61_fu_405_p2;
        icmp_ln61_reg_1198_pp0_iter2_reg <= icmp_ln61_reg_1198;
        in_valid_read_reg_1129 <= in_valid;
        in_valid_read_reg_1129_pp0_iter10_reg <= in_valid_read_reg_1129_pp0_iter9_reg;
        in_valid_read_reg_1129_pp0_iter11_reg <= in_valid_read_reg_1129_pp0_iter10_reg;
        in_valid_read_reg_1129_pp0_iter12_reg <= in_valid_read_reg_1129_pp0_iter11_reg;
        in_valid_read_reg_1129_pp0_iter13_reg <= in_valid_read_reg_1129_pp0_iter12_reg;
        in_valid_read_reg_1129_pp0_iter14_reg <= in_valid_read_reg_1129_pp0_iter13_reg;
        in_valid_read_reg_1129_pp0_iter15_reg <= in_valid_read_reg_1129_pp0_iter14_reg;
        in_valid_read_reg_1129_pp0_iter16_reg <= in_valid_read_reg_1129_pp0_iter15_reg;
        in_valid_read_reg_1129_pp0_iter17_reg <= in_valid_read_reg_1129_pp0_iter16_reg;
        in_valid_read_reg_1129_pp0_iter18_reg <= in_valid_read_reg_1129_pp0_iter17_reg;
        in_valid_read_reg_1129_pp0_iter1_reg <= in_valid_read_reg_1129;
        in_valid_read_reg_1129_pp0_iter2_reg <= in_valid_read_reg_1129_pp0_iter1_reg;
        in_valid_read_reg_1129_pp0_iter3_reg <= in_valid_read_reg_1129_pp0_iter2_reg;
        in_valid_read_reg_1129_pp0_iter4_reg <= in_valid_read_reg_1129_pp0_iter3_reg;
        in_valid_read_reg_1129_pp0_iter5_reg <= in_valid_read_reg_1129_pp0_iter4_reg;
        in_valid_read_reg_1129_pp0_iter6_reg <= in_valid_read_reg_1129_pp0_iter5_reg;
        in_valid_read_reg_1129_pp0_iter7_reg <= in_valid_read_reg_1129_pp0_iter6_reg;
        in_valid_read_reg_1129_pp0_iter8_reg <= in_valid_read_reg_1129_pp0_iter7_reg;
        in_valid_read_reg_1129_pp0_iter9_reg <= in_valid_read_reg_1129_pp0_iter8_reg;
        kInfraredScaleQ16_load_reg_1274 <= kInfraredScaleQ16_q0;
        kLaserScaleQ16_load_reg_1269 <= kLaserScaleQ16_q0;
        lut_idx_1_reg_1242 <= lut_idx_1_fu_537_p3;
        lut_idx_reg_1236 <= {{scaled_fu_516_p2[14:8]}};
        mapped_x_1_reg_1420 <= mapped_x_1_fu_974_p9;
        mapped_x_1_reg_1420_pp0_iter16_reg <= mapped_x_1_reg_1420;
        mapped_x_1_reg_1420_pp0_iter17_reg <= mapped_x_1_reg_1420_pp0_iter16_reg;
        mapped_x_1_reg_1420_pp0_iter18_reg <= mapped_x_1_reg_1420_pp0_iter17_reg;
        or_ln147_1_reg_1341 <= or_ln147_1_fu_713_p2;
        or_ln147_1_reg_1341_pp0_iter13_reg <= or_ln147_1_reg_1341;
        or_ln147_1_reg_1341_pp0_iter14_reg <= or_ln147_1_reg_1341_pp0_iter13_reg;
        out_slot_1_reg_1136 <= out_slot_1_fu_316_p1;
        out_slot_1_reg_1136_pp0_iter10_reg <= out_slot_1_reg_1136_pp0_iter9_reg;
        out_slot_1_reg_1136_pp0_iter11_reg <= out_slot_1_reg_1136_pp0_iter10_reg;
        out_slot_1_reg_1136_pp0_iter12_reg <= out_slot_1_reg_1136_pp0_iter11_reg;
        out_slot_1_reg_1136_pp0_iter13_reg <= out_slot_1_reg_1136_pp0_iter12_reg;
        out_slot_1_reg_1136_pp0_iter14_reg <= out_slot_1_reg_1136_pp0_iter13_reg;
        out_slot_1_reg_1136_pp0_iter15_reg <= out_slot_1_reg_1136_pp0_iter14_reg;
        out_slot_1_reg_1136_pp0_iter16_reg <= out_slot_1_reg_1136_pp0_iter15_reg;
        out_slot_1_reg_1136_pp0_iter17_reg <= out_slot_1_reg_1136_pp0_iter16_reg;
        out_slot_1_reg_1136_pp0_iter18_reg <= out_slot_1_reg_1136_pp0_iter17_reg;
        out_slot_1_reg_1136_pp0_iter1_reg <= out_slot_1_reg_1136;
        out_slot_1_reg_1136_pp0_iter2_reg <= out_slot_1_reg_1136_pp0_iter1_reg;
        out_slot_1_reg_1136_pp0_iter3_reg <= out_slot_1_reg_1136_pp0_iter2_reg;
        out_slot_1_reg_1136_pp0_iter4_reg <= out_slot_1_reg_1136_pp0_iter3_reg;
        out_slot_1_reg_1136_pp0_iter5_reg <= out_slot_1_reg_1136_pp0_iter4_reg;
        out_slot_1_reg_1136_pp0_iter6_reg <= out_slot_1_reg_1136_pp0_iter5_reg;
        out_slot_1_reg_1136_pp0_iter7_reg <= out_slot_1_reg_1136_pp0_iter6_reg;
        out_slot_1_reg_1136_pp0_iter8_reg <= out_slot_1_reg_1136_pp0_iter7_reg;
        out_slot_1_reg_1136_pp0_iter9_reg <= out_slot_1_reg_1136_pp0_iter8_reg;
        out_x_read_reg_1124 <= out_x;
        out_x_read_reg_1124_pp0_iter10_reg <= out_x_read_reg_1124_pp0_iter9_reg;
        out_x_read_reg_1124_pp0_iter11_reg <= out_x_read_reg_1124_pp0_iter10_reg;
        out_x_read_reg_1124_pp0_iter12_reg <= out_x_read_reg_1124_pp0_iter11_reg;
        out_x_read_reg_1124_pp0_iter13_reg <= out_x_read_reg_1124_pp0_iter12_reg;
        out_x_read_reg_1124_pp0_iter14_reg <= out_x_read_reg_1124_pp0_iter13_reg;
        out_x_read_reg_1124_pp0_iter1_reg <= out_x_read_reg_1124;
        out_x_read_reg_1124_pp0_iter2_reg <= out_x_read_reg_1124_pp0_iter1_reg;
        out_x_read_reg_1124_pp0_iter3_reg <= out_x_read_reg_1124_pp0_iter2_reg;
        out_x_read_reg_1124_pp0_iter4_reg <= out_x_read_reg_1124_pp0_iter3_reg;
        out_x_read_reg_1124_pp0_iter5_reg <= out_x_read_reg_1124_pp0_iter4_reg;
        out_x_read_reg_1124_pp0_iter6_reg <= out_x_read_reg_1124_pp0_iter5_reg;
        out_x_read_reg_1124_pp0_iter7_reg <= out_x_read_reg_1124_pp0_iter6_reg;
        out_x_read_reg_1124_pp0_iter8_reg <= out_x_read_reg_1124_pp0_iter7_reg;
        out_x_read_reg_1124_pp0_iter9_reg <= out_x_read_reg_1124_pp0_iter8_reg;
        packet_pixel_idx_read_reg_1119 <= packet_pixel_idx;
        packet_pixel_idx_read_reg_1119_pp0_iter10_reg <= packet_pixel_idx_read_reg_1119_pp0_iter9_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter11_reg <= packet_pixel_idx_read_reg_1119_pp0_iter10_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter12_reg <= packet_pixel_idx_read_reg_1119_pp0_iter11_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter13_reg <= packet_pixel_idx_read_reg_1119_pp0_iter12_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter14_reg <= packet_pixel_idx_read_reg_1119_pp0_iter13_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter15_reg <= packet_pixel_idx_read_reg_1119_pp0_iter14_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter16_reg <= packet_pixel_idx_read_reg_1119_pp0_iter15_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter17_reg <= packet_pixel_idx_read_reg_1119_pp0_iter16_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter18_reg <= packet_pixel_idx_read_reg_1119_pp0_iter17_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter1_reg <= packet_pixel_idx_read_reg_1119;
        packet_pixel_idx_read_reg_1119_pp0_iter2_reg <= packet_pixel_idx_read_reg_1119_pp0_iter1_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter3_reg <= packet_pixel_idx_read_reg_1119_pp0_iter2_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter4_reg <= packet_pixel_idx_read_reg_1119_pp0_iter3_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter5_reg <= packet_pixel_idx_read_reg_1119_pp0_iter4_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter6_reg <= packet_pixel_idx_read_reg_1119_pp0_iter5_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter7_reg <= packet_pixel_idx_read_reg_1119_pp0_iter6_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter8_reg <= packet_pixel_idx_read_reg_1119_pp0_iter7_reg;
        packet_pixel_idx_read_reg_1119_pp0_iter9_reg <= packet_pixel_idx_read_reg_1119_pp0_iter8_reg;
        radius_1_reg_1214 <= radius_1_fu_461_p1;
        radius_2_reg_1219 <= radius_2_fu_470_p3;
        radius_2_reg_1219_pp0_iter5_reg <= radius_2_reg_1219;
        radius_2_reg_1219_pp0_iter6_reg <= radius_2_reg_1219_pp0_iter5_reg;
        radius_reg_1209 <= radius_fu_455_p2;
        raw_delta_reg_1331 <= raw_delta_fu_697_p2;
        scale_q16_reg_1290 <= scale_q16_fu_610_p3;
        sel_tmp_reg_1263 <= sel_tmp_fu_584_p3;
        sel_tmp_reg_1263_pp0_iter10_reg <= sel_tmp_reg_1263;
        sel_tmp_reg_1263_pp0_iter11_reg <= sel_tmp_reg_1263_pp0_iter10_reg;
        sel_tmp_reg_1263_pp0_iter12_reg <= sel_tmp_reg_1263_pp0_iter11_reg;
        sel_tmp_reg_1263_pp0_iter13_reg <= sel_tmp_reg_1263_pp0_iter12_reg;
        sel_tmp_reg_1263_pp0_iter14_reg <= sel_tmp_reg_1263_pp0_iter13_reg;
        sel_tmp_reg_1263_pp0_iter15_reg <= sel_tmp_reg_1263_pp0_iter14_reg;
        sel_tmp_reg_1263_pp0_iter16_reg <= sel_tmp_reg_1263_pp0_iter15_reg;
        sel_tmp_reg_1263_pp0_iter17_reg <= sel_tmp_reg_1263_pp0_iter16_reg;
        sel_tmp_reg_1263_pp0_iter18_reg <= sel_tmp_reg_1263_pp0_iter17_reg;
        select_ln34_reg_1170 <= select_ln34_fu_358_p3;
        sext_ln32_reg_1192 <= sext_ln32_fu_402_p1;
        sext_ln32_reg_1192_pp0_iter2_reg <= sext_ln32_reg_1192;
        shift_1_reg_1430 <= shift_1_fu_1002_p2;
        slot_2_reg_1447 <= slot_2_fu_1069_p3;
        src_x_s_reg_1367 <= src_x_s_fu_753_p2;
        src_y_s_unclamped_reg_1373 <= src_y_s_unclamped_fu_762_p2;
        sub_ln63_reg_1204 <= sub_ln63_fu_427_p2;
        sub_ln74_1_reg_1231 <= sub_ln74_1_fu_500_p2;
        sub_ln74_reg_1226 <= sub_ln74_fu_480_p2;
        tmp_12_reg_1442 <= slot_fu_1046_p2[32'd9];
        tmp_3_reg_1301 <= {{grp_fu_604_p2[24:11]}};
        tmp_4_reg_1182 <= algo_ctrl[32'd3];
        tmp_4_reg_1182_pp0_iter10_reg <= tmp_4_reg_1182_pp0_iter9_reg;
        tmp_4_reg_1182_pp0_iter1_reg <= tmp_4_reg_1182;
        tmp_4_reg_1182_pp0_iter2_reg <= tmp_4_reg_1182_pp0_iter1_reg;
        tmp_4_reg_1182_pp0_iter3_reg <= tmp_4_reg_1182_pp0_iter2_reg;
        tmp_4_reg_1182_pp0_iter4_reg <= tmp_4_reg_1182_pp0_iter3_reg;
        tmp_4_reg_1182_pp0_iter5_reg <= tmp_4_reg_1182_pp0_iter4_reg;
        tmp_4_reg_1182_pp0_iter6_reg <= tmp_4_reg_1182_pp0_iter5_reg;
        tmp_4_reg_1182_pp0_iter7_reg <= tmp_4_reg_1182_pp0_iter6_reg;
        tmp_4_reg_1182_pp0_iter8_reg <= tmp_4_reg_1182_pp0_iter7_reg;
        tmp_4_reg_1182_pp0_iter9_reg <= tmp_4_reg_1182_pp0_iter8_reg;
        tmp_9_reg_1296 <= {{dist_to_line_1_fu_633_p3[12:8]}};
        trunc_ln158_reg_1306 <= trunc_ln158_fu_661_p1;
        trunc_ln167_reg_1436 <= trunc_ln167_fu_1052_p1;
        trunc_ln175_reg_1452 <= trunc_ln175_fu_1075_p1;
        trunc_ln190_reg_1142 <= trunc_ln190_fu_320_p1;
        trunc_ln190_reg_1142_pp0_iter1_reg <= trunc_ln190_reg_1142;
        trunc_ln190_reg_1142_pp0_iter2_reg <= trunc_ln190_reg_1142_pp0_iter1_reg;
        trunc_ln190_reg_1142_pp0_iter3_reg <= trunc_ln190_reg_1142_pp0_iter2_reg;
        trunc_ln190_reg_1142_pp0_iter4_reg <= trunc_ln190_reg_1142_pp0_iter3_reg;
        trunc_ln190_reg_1142_pp0_iter5_reg <= trunc_ln190_reg_1142_pp0_iter4_reg;
        trunc_ln190_reg_1142_pp0_iter6_reg <= trunc_ln190_reg_1142_pp0_iter5_reg;
        trunc_ln190_reg_1142_pp0_iter7_reg <= trunc_ln190_reg_1142_pp0_iter6_reg;
        trunc_ln190_reg_1142_pp0_iter8_reg <= trunc_ln190_reg_1142_pp0_iter7_reg;
        trunc_ln211_reg_1405 <= trunc_ln211_fu_863_p1;
        trunc_ln215_reg_1415 <= trunc_ln215_fu_932_p1;
        trunc_ln82_1_reg_1352 <= {{grp_fu_683_p2[29:16]}};
        trunc_ln_reg_1347 <= {{grp_fu_674_p2[28:16]}};
        weight_reg_1336 <= weight_fu_703_p2;
        weighted_reg_1384 <= grp_fu_744_p2;
        zext_ln196_reg_1147[10 : 0] <= zext_ln196_fu_324_p1[10 : 0];
        zext_ln196_reg_1147_pp0_iter1_reg[10 : 0] <= zext_ln196_reg_1147[10 : 0];
        zext_ln196_reg_1147_pp0_iter2_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter1_reg[10 : 0];
        zext_ln196_reg_1147_pp0_iter3_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter2_reg[10 : 0];
        zext_ln196_reg_1147_pp0_iter4_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter3_reg[10 : 0];
        zext_ln196_reg_1147_pp0_iter5_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter4_reg[10 : 0];
        zext_ln196_reg_1147_pp0_iter6_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter5_reg[10 : 0];
        zext_ln196_reg_1147_pp0_iter7_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter6_reg[10 : 0];
        zext_ln196_reg_1147_pp0_iter8_reg[10 : 0] <= zext_ln196_reg_1147_pp0_iter7_reg[10 : 0];
        zext_ln197_reg_1158[11 : 0] <= zext_ln197_fu_334_p1[11 : 0];
        zext_ln197_reg_1158_pp0_iter10_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter9_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter11_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter10_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter12_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter11_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter13_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter12_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter14_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter13_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter1_reg[11 : 0] <= zext_ln197_reg_1158[11 : 0];
        zext_ln197_reg_1158_pp0_iter2_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter1_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter3_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter2_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter4_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter3_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter5_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter4_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter6_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter5_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter7_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter6_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter8_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter7_reg[11 : 0];
        zext_ln197_reg_1158_pp0_iter9_reg[11 : 0] <= zext_ln197_reg_1158_pp0_iter8_reg[11 : 0];
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        kInfraredScaleQ16_ce0_local = 1'b1;
    end else begin
        kInfraredScaleQ16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        kLaserScaleQ16_ce0_local = 1'b1;
    end else begin
        kLaserScaleQ16_ce0_local = 1'b0;
    end
end

assign abs_dx_1_fu_567_p3 = ((tmp_7_fu_554_p3[0:0] == 1'b1) ? abs_dx_fu_562_p2 : dx_1_fu_549_p2);

assign abs_dx_fu_562_p2 = (12'd964 - zext_ln196_reg_1147_pp0_iter8_reg);

assign add_ln126_fu_998_p2 = (trunc_ln211_reg_1405 + trunc_ln215_reg_1415);

assign add_ln174_fu_1084_p2 = (trunc_ln175_reg_1452 + 8'd56);

assign and_ln120_fu_899_p2 = (xor_ln147_fu_894_p2 & icmp_ln120_fu_867_p2);

assign and_ln190_fu_575_p2 = (trunc_ln190_reg_1142_pp0_iter8_reg & in_valid_read_reg_1129_pp0_iter8_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign base_delta_line_fu_858_p2 = (zext_ln211_fu_854_p1 - zext_ln197_reg_1158_pp0_iter14_reg);

assign curve_delta_line_fu_912_p6 = ((icmp_ln123_fu_872_p2[0:0] == 1'b1) ? 13'd8096 : trunc_ln3_fu_877_p4);

assign curve_delta_line_fu_912_p7 = 'bx;

assign curve_delta_line_fu_912_p8 = {{or_ln147_1_reg_1341_pp0_iter14_reg}, {and_ln120_fu_899_p2}};

assign delta_fu_380_p3 = ((tmp_2_fu_366_p3[0:0] == 1'b1) ? sub_ln34_1_fu_374_p2 : dy_fu_338_p2);

assign dist_to_line_1_fu_633_p3 = ((tmp_8_fu_620_p3[0:0] == 1'b1) ? dist_to_line_fu_628_p2 : line_delta_fu_615_p2);

assign dist_to_line_fu_628_p2 = (13'd1606 - zext_ln197_reg_1158_pp0_iter10_reg);

assign dx_1_fu_549_p2 = ($signed(zext_ln196_reg_1147_pp0_iter8_reg) + $signed(12'd3132));

assign dx_fu_328_p2 = ($signed(zext_ln196_fu_324_p1) + $signed(12'd3137));

assign dy_fu_338_p2 = ($signed(zext_ln197_fu_334_p1) + $signed(13'd7205));

assign grp_fu_604_p0 = zext_ln154_fu_600_p1;

assign grp_fu_604_p1 = zext_ln154_fu_600_p1;

assign grp_fu_674_p0 = grp_fu_674_p00;

assign grp_fu_674_p00 = scale_q16_reg_1290;

assign grp_fu_683_p0 = grp_fu_683_p00;

assign grp_fu_683_p00 = scale_q16_reg_1290;

assign grp_fu_744_p1 = grp_fu_744_p10;

assign grp_fu_744_p10 = weight_reg_1336;

assign icmp_ln120_1_fu_1008_p2 = (($signed(shift_1_reg_1430) > $signed(14'd96)) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_867_p2 = (($signed(delta_4_reg_1389) > $signed(16'd96)) ? 1'b1 : 1'b0);

assign icmp_ln123_1_fu_1013_p2 = (($signed(shift_1_reg_1430) < $signed(14'd16288)) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_872_p2 = (($signed(delta_4_reg_1389) < $signed(16'd65440)) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_396_p2 = ((out_line < 12'd981) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_592_p2 = ((abs_dx_1_reg_1257 > 12'd760) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_689_p2 = ((tmp_9_reg_1296 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_1079_p2 = ((slot_2_reg_1447 > 9'd199) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_804_p2 = (($signed(tmp_11_fu_794_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_778_p2 = (($signed(tmp_6_fu_768_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_405_p2 = ((sext_ln32_fu_402_p1 > delta_reg_1175) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_465_p2 = ((radius_reg_1209 > 14'd947) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_532_p2 = ((lut_idx_reg_1236 > 7'd100) ? 1'b1 : 1'b0);

assign kInfraredScaleQ16_address0 = zext_ln200_fu_544_p1;

assign kLaserScaleQ16_address0 = zext_ln200_fu_544_p1;

assign line_delta_fu_615_p2 = ($signed(zext_ln197_reg_1158_pp0_iter10_reg) + $signed(13'd6586));

assign lut_idx_1_fu_537_p3 = ((icmp_ln76_fu_532_p2[0:0] == 1'b1) ? 7'd100 : lut_idx_reg_1236);

assign mapped_slot_1_fu_1096_p2 = ((icmp_ln174_fu_1079_p2[0:0] == 1'b1) ? add_ln174_fu_1084_p2 : trunc_ln175_reg_1452);

assign mapped_slot_1_fu_1096_p7 = 'bx;

assign mapped_x_1_fu_974_p2 = ((or_ln39_fu_961_p2[0:0] == 1'b1) ? select_ln39_fu_953_p3 : trunc_ln45_fu_944_p1);

assign mapped_x_1_fu_974_p7 = 'bx;

assign max_v_fu_433_p3 = ((icmp_ln61_reg_1198_pp0_iter2_reg[0:0] == 1'b1) ? sext_ln32_reg_1192_pp0_iter2_reg : delta_reg_1175_pp0_iter2_reg);

assign min_v_fu_410_p3 = ((icmp_ln61_reg_1198[0:0] == 1'b1) ? delta_reg_1175_pp0_iter1_reg : sext_ln32_reg_1192);

assign or_ln120_fu_1026_p2 = (icmp_ln123_1_fu_1013_p2 | icmp_ln120_1_fu_1008_p2);

assign or_ln147_1_fu_713_p2 = (or_ln147_fu_708_p2 | icmp_ln135_reg_1187_pp0_iter11_reg);

assign or_ln147_fu_708_p2 = (icmp_ln147_fu_689_p2 | icmp_ln141_reg_1279_pp0_iter11_reg);

assign or_ln39_fu_961_p2 = (tmp_10_fu_936_p3 | icmp_ln42_reg_1395);

assign or_ln50_fu_841_p2 = (tmp_5_fu_816_p3 | icmp_ln53_reg_1379);

assign out_slot_1_fu_316_p1 = out_slot[7:0];

assign out_valid = in_valid_read_reg_1129_pp0_iter18_reg;

assign p_shl_fu_419_p3 = {{min_v_fu_410_p3}, {2'd0}};

assign packet_pixel_idx_out = packet_pixel_idx_read_reg_1119_pp0_iter18_reg;

assign radius_1_fu_461_p1 = radius_fu_455_p2[9:0];

assign radius_2_fu_470_p3 = ((icmp_ln64_fu_465_p2[0:0] == 1'b1) ? 10'd947 : radius_1_reg_1214);

assign radius_fu_455_p2 = (zext_ln63_2_fu_451_p1 + zext_ln63_fu_438_p1);

assign raw_delta_fu_697_p2 = (15'd135 - zext_ln157_fu_694_p1);

assign safe_delta_line_fu_1032_p3 = ((or_ln120_fu_1026_p2[0:0] == 1'b1) ? select_ln120_fu_1018_p3 : add_ln126_reg_1425);

assign scale_q16_fu_610_p3 = ((tmp_4_reg_1182_pp0_iter10_reg[0:0] == 1'b1) ? kLaserScaleQ16_load_reg_1269 : kInfraredScaleQ16_load_reg_1274);

assign scaled_fu_516_p2 = ($signed(sext_ln74_1_fu_513_p1) + $signed(shl_ln74_1_fu_506_p3));

assign sel_tmp_fu_584_p3 = {{and_ln190_fu_575_p2}, {xor_ln222_fu_579_p2}};

assign select_ln120_fu_1018_p3 = ((icmp_ln120_1_fu_1008_p2[0:0] == 1'b1) ? 8'd96 : 8'd160);

assign select_ln34_fu_358_p3 = ((tmp_1_fu_344_p3[0:0] == 1'b1) ? sub_ln34_fu_352_p2 : dx_fu_328_p2);

assign select_ln39_fu_953_p3 = ((xor_ln39_fu_947_p2[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign select_ln50_fu_833_p3 = ((xor_ln50_fu_827_p2[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign sext_ln154_fu_597_p1 = abs_dx_1_reg_1257;

assign sext_ln167_fu_1039_p1 = $signed(safe_delta_line_fu_1032_p3);

assign sext_ln208_1_fu_810_p1 = src_x_s_reg_1367;

assign sext_ln208_fu_750_p1 = $signed(trunc_ln_reg_1347);

assign sext_ln209_1_fu_813_p1 = src_y_s_unclamped_reg_1373;

assign sext_ln209_fu_759_p1 = $signed(trunc_ln82_1_reg_1352);

assign sext_ln211_fu_992_p1 = base_delta_line_reg_1400;

assign sext_ln216_fu_995_p1 = curve_delta_line_reg_1410;

assign sext_ln32_fu_402_p1 = $signed(select_ln34_reg_1170);

assign sext_ln74_1_fu_513_p1 = $signed(sub_ln74_1_reg_1231);

assign sext_ln74_fu_497_p1 = $signed(sub_ln74_reg_1226);

assign shift_1_fu_1002_p2 = ($signed(sext_ln211_fu_992_p1) + $signed(sext_ln216_fu_995_p1));

assign shl_ln74_1_fu_506_p3 = {{radius_2_reg_1219_pp0_iter6_reg}, {5'd0}};

assign shl_ln_fu_486_p3 = {{radius_2_reg_1219_pp0_iter5_reg}, {2'd0}};

assign slot_1_fu_1064_p2 = (trunc_ln167_reg_1436 + 9'd200);

assign slot_2_fu_1069_p3 = ((tmp_12_reg_1442[0:0] == 1'b1) ? slot_1_fu_1064_p2 : trunc_ln167_reg_1436);

assign slot_fu_1046_p2 = ($signed(sext_ln167_fu_1039_p1) + $signed(zext_ln167_fu_1043_p1));

assign src_slot = mapped_slot_1_fu_1096_p9;

assign src_x = mapped_x_1_reg_1420_pp0_iter18_reg;

assign src_x_s_fu_753_p2 = ($signed(sext_ln208_fu_750_p1) + $signed(14'd959));

assign src_y_fu_846_p3 = ((or_ln50_fu_841_p2[0:0] == 1'b1) ? select_ln50_fu_833_p3 : trunc_ln56_fu_824_p1);

assign src_y_s_unclamped_fu_762_p2 = ($signed(sext_ln209_fu_759_p1) + $signed(15'd987));

assign sub_ln34_1_fu_374_p2 = (13'd987 - zext_ln197_fu_334_p1);

assign sub_ln34_fu_352_p2 = (12'd959 - zext_ln196_fu_324_p1);

assign sub_ln63_fu_427_p2 = (p_shl_fu_419_p3 - zext_ln63_1_fu_415_p1);

assign sub_ln74_1_fu_500_p2 = ($signed(sext_ln74_fu_497_p1) - $signed(zext_ln74_1_fu_493_p1));

assign sub_ln74_fu_480_p2 = (11'd128 - zext_ln74_fu_477_p1);

assign tmp_10_fu_936_p3 = sext_ln208_1_fu_810_p1[32'd15];

assign tmp_11_fu_794_p4 = {{src_x_s_fu_753_p2[13:11]}};

assign tmp_1_fu_344_p3 = dx_fu_328_p2[32'd11];

assign tmp_2_fu_366_p3 = dy_fu_338_p2[32'd12];

assign tmp_5_fu_816_p3 = sext_ln209_1_fu_813_p1[32'd15];

assign tmp_6_fu_768_p4 = {{src_y_s_unclamped_fu_762_p2[14:11]}};

assign tmp_7_fu_554_p3 = dx_1_fu_549_p2[32'd11];

assign tmp_8_fu_620_p3 = line_delta_fu_615_p2[32'd12];

assign tmp_fu_442_p4 = {{sub_ln63_reg_1204[14:3]}};

assign trunc_ln158_fu_661_p1 = dist_to_line_1_fu_633_p3[8:0];

assign trunc_ln167_fu_1052_p1 = slot_fu_1046_p2[8:0];

assign trunc_ln175_fu_1075_p1 = slot_2_fu_1069_p3[7:0];

assign trunc_ln190_fu_320_p1 = algo_ctrl[0:0];

assign trunc_ln211_fu_863_p1 = base_delta_line_fu_858_p2[7:0];

assign trunc_ln215_fu_932_p1 = curve_delta_line_fu_912_p9[7:0];

assign trunc_ln3_fu_877_p4 = {{weighted_reg_1384[20:8]}};

assign trunc_ln45_fu_944_p1 = src_x_s_reg_1367[10:0];

assign trunc_ln56_fu_824_p1 = src_y_s_unclamped_reg_1373[10:0];

assign weight_fu_703_p2 = ($signed(9'd256) - $signed(trunc_ln158_reg_1306));

assign xor_ln147_fu_894_p2 = (or_ln147_1_reg_1341_pp0_iter14_reg ^ 1'd1);

assign xor_ln222_fu_579_p2 = (in_valid_read_reg_1129_pp0_iter8_reg ^ 1'd1);

assign xor_ln39_fu_947_p2 = (tmp_10_fu_936_p3 ^ 1'd1);

assign xor_ln50_fu_827_p2 = (tmp_5_fu_816_p3 ^ 1'd1);

assign zext_ln154_fu_600_p1 = $unsigned(sext_ln154_fu_597_p1);

assign zext_ln157_fu_694_p1 = tmp_3_reg_1301;

assign zext_ln167_fu_1043_p1 = out_slot_1_reg_1136_pp0_iter16_reg;

assign zext_ln196_fu_324_p1 = out_x;

assign zext_ln197_fu_334_p1 = out_line;

assign zext_ln200_fu_544_p1 = lut_idx_1_reg_1242;

assign zext_ln211_fu_854_p1 = src_y_fu_846_p3;

assign zext_ln63_1_fu_415_p1 = min_v_fu_410_p3;

assign zext_ln63_2_fu_451_p1 = tmp_fu_442_p4;

assign zext_ln63_fu_438_p1 = max_v_fu_433_p3;

assign zext_ln74_1_fu_493_p1 = shl_ln_fu_486_p3;

assign zext_ln74_fu_477_p1 = radius_2_reg_1219;

always @ (posedge ap_clk) begin
    zext_ln196_reg_1147[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter1_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter2_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter3_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter4_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter5_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter6_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter7_reg[11] <= 1'b0;
    zext_ln196_reg_1147_pp0_iter8_reg[11] <= 1'b0;
    zext_ln197_reg_1158[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter1_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter2_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter3_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter4_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter5_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter6_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter7_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter8_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter9_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter10_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter11_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter12_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter13_reg[12] <= 1'b0;
    zext_ln197_reg_1158_pp0_iter14_reg[12] <= 1'b0;
end

endmodule //fisheye_remap_addr_hls
