// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fisheye_remap_reader_hls_fisheye_remap_reader_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100-ffg900-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.888571,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1186,HLS_SYN_LUT=1169,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module fisheye_remap_reader_hls (
        ap_clk,
        ap_rst,
        bram_line_cur_w,
        bram_line_cur_w_en,
        bram_line_num,
        bram_doutb,
        fifo_almost_full,
        algo_ctrl,
        bram_line_num_addr,
        bram_addrb,
        fifo_wr_en,
        fifo_din
);

parameter    ap_ST_fsm_state1 = 33'd1;
parameter    ap_ST_fsm_state2 = 33'd2;
parameter    ap_ST_fsm_state3 = 33'd4;
parameter    ap_ST_fsm_state4 = 33'd8;
parameter    ap_ST_fsm_state5 = 33'd16;
parameter    ap_ST_fsm_state6 = 33'd32;
parameter    ap_ST_fsm_state7 = 33'd64;
parameter    ap_ST_fsm_state8 = 33'd128;
parameter    ap_ST_fsm_state9 = 33'd256;
parameter    ap_ST_fsm_state10 = 33'd512;
parameter    ap_ST_fsm_state11 = 33'd1024;
parameter    ap_ST_fsm_state12 = 33'd2048;
parameter    ap_ST_fsm_state13 = 33'd4096;
parameter    ap_ST_fsm_state14 = 33'd8192;
parameter    ap_ST_fsm_state15 = 33'd16384;
parameter    ap_ST_fsm_state16 = 33'd32768;
parameter    ap_ST_fsm_state17 = 33'd65536;
parameter    ap_ST_fsm_state18 = 33'd131072;
parameter    ap_ST_fsm_state19 = 33'd262144;
parameter    ap_ST_fsm_state20 = 33'd524288;
parameter    ap_ST_fsm_state21 = 33'd1048576;
parameter    ap_ST_fsm_state22 = 33'd2097152;
parameter    ap_ST_fsm_state23 = 33'd4194304;
parameter    ap_ST_fsm_state24 = 33'd8388608;
parameter    ap_ST_fsm_state25 = 33'd16777216;
parameter    ap_ST_fsm_state26 = 33'd33554432;
parameter    ap_ST_fsm_state27 = 33'd67108864;
parameter    ap_ST_fsm_state28 = 33'd134217728;
parameter    ap_ST_fsm_state29 = 33'd268435456;
parameter    ap_ST_fsm_state30 = 33'd536870912;
parameter    ap_ST_fsm_state31 = 33'd1073741824;
parameter    ap_ST_fsm_state32 = 33'd2147483648;
parameter    ap_ST_fsm_state33 = 33'd4294967296;

input   ap_clk;
input   ap_rst;
input  [18:0] bram_line_cur_w;
input  [0:0] bram_line_cur_w_en;
input  [11:0] bram_line_num;
input  [15:0] bram_doutb;
input  [0:0] fifo_almost_full;
input  [31:0] algo_ctrl;
output  [8:0] bram_line_num_addr;
output  [18:0] bram_addrb;
output  [0:0] fifo_wr_en;
output  [64:0] fifo_din;

reg[0:0] fifo_wr_en;
reg[64:0] fifo_din;

reg   [18:0] bram_addr_reg;
reg   [7:0] line_num_addr_reg;
reg   [0:0] video_started;
reg   [2:0] state;
reg   [11:0] out_line;
reg   [3:0] packet_idx;
reg   [11:0] line_pixel_idx;
reg   [64:0] payload_word;
reg   [15:0] adaptive_black;
reg   [15:0] adaptive_gain_q8;
reg   [15:0] frame_min;
reg   [15:0] frame_max;
reg   [7:0] out_slot;
reg   [6:0] packet_pixel_idx;
reg   [1:0] pack_idx;
reg   [0:0] payload_last;
wire   [6:0] kLaserScaleQ16_address0;
wire   [12:0] kLaserScaleQ16_q0;
wire   [6:0] kInfraredScaleQ16_address0;
wire   [12:0] kInfraredScaleQ16_q0;
reg   [15:0] source_pixel_reg;
reg   [0:0] adaptive_valid;
reg   [31:0] algo_ctrl_read_reg_1884;
(* fsm_encoding = "none" *) reg   [32:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] fifo_almost_full_read_read_fu_328_p2;
reg   [0:0] fifo_almost_full_read_reg_1893;
wire   [0:0] bram_line_cur_w_en_read_read_fu_346_p2;
reg   [0:0] bram_line_cur_w_en_read_reg_1897;
wire   [2:0] state_load_load_fu_471_p1;
reg   [2:0] state_load_reg_1904;
reg   [11:0] out_y_reg_1908;
reg   [3:0] packet_idx_load_reg_1914;
reg   [11:0] line_pixel_idx_load_reg_1920;
reg   [64:0] payload_word_load_reg_1927;
reg   [15:0] adaptive_black_1_reg_1936;
reg   [15:0] adaptive_gain_q8_1_reg_1942;
reg   [15:0] new_value_reg_1949;
reg   [15:0] frame_max_load_reg_1956;
wire   [15:0] shifted_1_fu_577_p3;
reg   [15:0] shifted_1_reg_1978;
wire   [10:0] out_x_fu_603_p1;
reg   [10:0] out_x_reg_1983;
wire   [0:0] bit_sel_fu_611_p3;
reg   [0:0] bit_sel_reg_1988;
wire   [0:0] xor_ln125_fu_619_p2;
reg   [0:0] xor_ln125_reg_1993;
wire   [12:0] zext_ln126_fu_625_p1;
reg   [12:0] zext_ln126_reg_1998;
wire  signed [12:0] dy_fu_629_p2;
reg  signed [12:0] dy_reg_2003;
wire   [11:0] sub_ln34_fu_635_p2;
reg   [11:0] sub_ln34_reg_2008;
wire   [12:0] delta_fu_655_p3;
reg   [12:0] delta_reg_2013;
wire   [0:0] or_ln263_fu_725_p2;
reg   [0:0] or_ln263_reg_2020;
wire    ap_CS_fsm_state2;
reg   [7:0] tmp_19_reg_2034;
wire    ap_CS_fsm_state3;
reg   [15:0] output_pixel_reg_2039;
wire   [15:0] output_pixel_3_fu_794_p3;
reg   [15:0] output_pixel_3_reg_2044;
wire    ap_CS_fsm_state4;
wire   [0:0] trunc_ln119_fu_946_p1;
reg   [0:0] trunc_ln119_reg_2052;
wire    ap_CS_fsm_state7;
wire  signed [10:0] dx_fu_952_p3;
reg  signed [10:0] dx_reg_2058;
wire  signed [12:0] sext_ln32_fu_969_p1;
reg  signed [12:0] sext_ln32_reg_2063;
wire   [0:0] icmp_ln61_fu_973_p2;
reg   [0:0] icmp_ln61_reg_2069;
reg   [0:0] tmp_2_reg_2075;
wire   [14:0] sub_ln63_fu_1002_p2;
reg   [14:0] sub_ln63_reg_2080;
wire    ap_CS_fsm_state8;
wire   [13:0] radius_fu_1030_p2;
reg   [13:0] radius_reg_2085;
wire    ap_CS_fsm_state9;
wire   [10:0] radius_1_fu_1036_p1;
reg   [10:0] radius_1_reg_2090;
wire   [10:0] radius_2_fu_1045_p3;
reg   [10:0] radius_2_reg_2095;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg   [6:0] lut_idx_reg_2105;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg   [12:0] kLaserScaleQ16_load_reg_2120;
wire    ap_CS_fsm_state16;
reg   [12:0] kInfraredScaleQ16_load_reg_2125;
wire   [12:0] scale_q16_1_fu_1069_p3;
reg   [12:0] scale_q16_1_reg_2130;
wire    ap_CS_fsm_state17;
wire  signed [15:0] trunc_ln_fu_1102_p4;
reg  signed [15:0] trunc_ln_reg_2136;
wire    ap_CS_fsm_state18;
wire   [0:0] xor_ln91_fu_1124_p2;
reg   [0:0] xor_ln91_reg_2141;
wire    ap_CS_fsm_state19;
reg   [11:0] tmp_6_reg_2166;
wire    ap_CS_fsm_state20;
reg   [13:0] tmp_7_reg_2171;
wire  signed [13:0] src_x_s_fu_1185_p2;
reg  signed [13:0] src_x_s_reg_2176;
wire    ap_CS_fsm_state21;
wire   [15:0] src_y_s_fu_1194_p2;
reg   [15:0] src_y_s_reg_2182;
reg   [0:0] tmp_8_reg_2187;
wire   [0:0] icmp_ln53_fu_1218_p2;
reg   [0:0] icmp_ln53_reg_2193;
wire   [0:0] icmp_ln42_fu_1234_p2;
reg   [0:0] icmp_ln42_reg_2198;
wire   [12:0] delta_line_fu_1313_p2;
reg   [12:0] delta_line_reg_2203;
wire    ap_CS_fsm_state22;
wire   [10:0] src_x_1_fu_1318_p3;
reg   [10:0] src_x_1_reg_2208;
wire   [12:0] slot_fu_1332_p2;
reg   [12:0] slot_reg_2216;
wire    ap_CS_fsm_state23;
reg   [0:0] tmp_15_reg_2222;
wire   [12:0] slot_2_fu_1350_p3;
reg   [12:0] slot_2_reg_2227;
wire    ap_CS_fsm_state24;
reg   [0:0] tmp_16_reg_2233;
wire   [12:0] slot_4_fu_1369_p3;
reg   [12:0] slot_4_reg_2238;
wire    ap_CS_fsm_state25;
wire   [12:0] slot_6_fu_1385_p3;
reg   [12:0] slot_6_reg_2245;
wire    ap_CS_fsm_state26;
wire   [7:0] trunc_ln107_fu_1392_p1;
reg   [7:0] trunc_ln107_reg_2250;
wire   [0:0] icmp_ln365_fu_1535_p2;
reg   [0:0] icmp_ln365_reg_2262;
wire    ap_CS_fsm_state30;
wire   [0:0] tmp_18_fu_1540_p3;
reg   [0:0] tmp_18_reg_2266;
wire   [15:0] frame_span_fu_1547_p2;
reg   [15:0] frame_span_reg_2270;
wire   [0:0] trunc_ln367_fu_1551_p1;
reg   [0:0] trunc_ln367_reg_2278;
reg   [0:0] adaptive_valid_load_reg_2282;
reg   [0:0] tmp_20_reg_2286;
wire   [0:0] icmp_ln367_fu_1575_p2;
reg   [0:0] icmp_ln367_reg_2291;
wire   [0:0] or_ln367_fu_1581_p2;
reg   [0:0] or_ln367_reg_2296;
wire    ap_CS_fsm_state31;
wire   [15:0] zext_ln368_fu_1709_p1;
reg   [15:0] zext_ln368_reg_2300;
wire   [17:0] sub_ln170_fu_1731_p2;
reg   [17:0] sub_ln170_reg_2305;
wire   [16:0] add_ln170_fu_1737_p2;
reg   [16:0] add_ln170_reg_2310;
wire   [17:0] sub_ln170_1_fu_1753_p2;
reg   [17:0] sub_ln170_1_reg_2315;
reg   [11:0] tmp_13_reg_2320;
wire   [0:0] trunc_ln170_fu_1769_p1;
reg   [0:0] trunc_ln170_reg_2325;
reg   [15:0] output_pixel_1_reg_415;
wire   [0:0] tmp_17_fu_533_p3;
wire   [0:0] trunc_ln317_fu_529_p1;
wire    ap_CS_fsm_state5;
reg   [1:0] storemerge958_0_0_027_reg_424;
wire   [0:0] payload_last_load_load_fu_1491_p1;
wire   [0:0] icmp_ln363_fu_1519_p2;
wire    ap_CS_fsm_state32;
wire   [63:0] zext_ln129_fu_1064_p1;
wire   [18:0] or4_i_fu_1419_p3;
wire    ap_CS_fsm_state27;
wire   [7:0] add_ln27_fu_739_p2;
wire   [0:0] icmp_ln257_fu_459_p2;
reg   [0:0] ap_sig_allocacmp_video_started_load;
wire   [2:0] storemerge958_0_0_027_cast_fu_1865_p1;
wire   [2:0] select_ln345_fu_926_p3;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state6;
wire   [3:0] add_ln386_fu_1524_p2;
wire   [11:0] add_ln342_fu_891_p2;
wire   [64:0] tmp_11_fu_815_p4;
wire   [64:0] tmp_10_fu_830_p4;
wire   [64:0] tmp_5_fu_845_p4;
wire   [64:0] tmp_1_fu_860_p4;
wire   [1:0] pack_idx_load_load_fu_801_p1;
wire   [0:0] icmp_ln318_fu_541_p2;
wire   [0:0] icmp_ln321_fu_553_p2;
wire   [6:0] add_ln343_fu_902_p2;
wire   [1:0] add_ln349_fu_920_p2;
wire   [0:0] icmp_ln340_fu_879_p2;
wire   [64:0] zext_ln284_1_fu_1462_p1;
wire   [64:0] or_ln_fu_1498_p3;
reg    kLaserScaleQ16_ce0_local;
reg    kInfraredScaleQ16_ce0_local;
wire   [7:0] trunc_ln257_fu_455_p1;
wire   [0:0] icmp_ln184_fu_565_p2;
wire   [15:0] shifted_fu_571_p2;
wire   [11:0] zext_ln125_fu_607_p1;
wire   [0:0] tmp_fu_641_p3;
wire   [12:0] sub_ln34_1_fu_649_p2;
wire   [7:0] cur_slot_fu_715_p1;
wire   [0:0] icmp_ln263_fu_719_p2;
wire   [7:0] select_ln27_fu_731_p3;
wire   [15:0] grp_fu_763_p0;
wire   [15:0] grp_fu_763_p1;
wire   [31:0] grp_fu_763_p2;
wire   [0:0] icmp_ln145_fu_789_p2;
wire   [0:0] icmp_ln345_fu_914_p2;
wire   [9:0] trunc_ln125_fu_949_p1;
wire  signed [11:0] sext_ln125_fu_959_p1;
wire   [11:0] select_ln34_fu_963_p3;
wire   [12:0] min_v_fu_985_p3;
wire   [14:0] p_shl1_fu_994_p3;
wire   [14:0] zext_ln63_1_fu_990_p1;
wire   [12:0] max_v_fu_1008_p3;
wire   [11:0] tmp_s_fu_1017_p4;
wire   [13:0] zext_ln63_2_fu_1026_p1;
wire   [13:0] zext_ln63_fu_1013_p1;
wire   [0:0] icmp_ln64_fu_1040_p2;
wire   [16:0] grp_fu_1875_p3;
wire   [22:0] tmp_3_fu_1074_p3;
wire   [20:0] tmp_4_fu_1085_p3;
wire  signed [23:0] sext_ln84_fu_1081_p1;
wire  signed [23:0] sext_ln84_1_fu_1092_p1;
wire   [23:0] sub_ln84_fu_1096_p2;
wire  signed [16:0] sext_ln91_fu_1112_p1;
wire   [0:0] bit_sel1_fu_1116_p3;
wire   [16:0] amplified_scale_q16_fu_1130_p3;
wire   [16:0] grp_fu_1147_p0;
wire   [16:0] grp_fu_1156_p0;
wire   [27:0] grp_fu_1147_p2;
wire   [29:0] grp_fu_1156_p2;
wire  signed [13:0] sext_ln136_fu_1182_p1;
wire  signed [15:0] sext_ln77_fu_1191_p1;
wire   [4:0] tmp_9_fu_1208_p4;
wire   [2:0] tmp_14_fu_1224_p4;
wire   [0:0] xor_ln50_fu_1246_p2;
wire   [0:0] or_ln50_fu_1259_p2;
wire   [10:0] select_ln50_fu_1251_p3;
wire   [10:0] trunc_ln56_fu_1243_p1;
wire  signed [15:0] sext_ln136_1_fu_1240_p1;
wire   [0:0] tmp_12_fu_1271_p3;
wire   [0:0] xor_ln39_fu_1282_p2;
wire   [0:0] or_ln39_fu_1296_p2;
wire   [10:0] select_ln39_fu_1288_p3;
wire   [10:0] trunc_ln45_fu_1279_p1;
wire   [10:0] src_y_fu_1263_p3;
wire   [12:0] zext_ln140_fu_1309_p1;
wire   [10:0] src_x_fu_1301_p3;
wire   [12:0] zext_ln96_fu_1328_p1;
wire   [12:0] slot_1_fu_1345_p2;
wire   [12:0] slot_3_fu_1364_p2;
wire   [0:0] icmp_ln103_fu_1375_p2;
wire   [12:0] slot_5_fu_1380_p2;
wire   [0:0] icmp_ln106_fu_1396_p2;
wire   [7:0] add_ln106_fu_1401_p2;
wire   [7:0] src_slot_fu_1406_p3;
wire   [7:0] src_slot_1_fu_1413_p3;
wire   [23:0] srio_addr_fu_1438_p4;
wire   [44:0] zext_ln284_fu_1446_p1;
wire   [53:0] or_ln1_fu_1450_p3;
wire  signed [54:0] sext_ln284_fu_1458_p1;
wire   [63:0] trunc_ln357_fu_1495_p1;
wire   [5:0] tmp_21_fu_1565_p4;
wire   [1:0] tmp_23_fu_1592_p4;
wire   [2:0] tmp_24_fu_1607_p4;
wire   [3:0] tmp_25_fu_1622_p4;
wire   [0:0] icmp_ln162_fu_1631_p2;
wire   [0:0] tmp_22_fu_1585_p3;
wire   [0:0] icmp_ln156_fu_1601_p2;
wire   [0:0] xor_ln153_fu_1645_p2;
wire   [0:0] or_ln156_fu_1657_p2;
wire   [0:0] icmp_ln159_fu_1616_p2;
wire   [0:0] xor_ln156_fu_1663_p2;
wire   [0:0] and_ln156_fu_1651_p2;
wire   [0:0] and_ln159_fu_1669_p2;
wire   [13:0] target_gain_q8_fu_1685_p8;
wire   [13:0] target_gain_q8_fu_1685_p9;
wire   [2:0] target_gain_q8_fu_1685_p10;
wire   [13:0] target_gain_q8_fu_1685_p11;
wire   [17:0] p_shl2_fu_1724_p3;
wire   [17:0] zext_ln170_fu_1718_p1;
wire   [16:0] zext_ln170_1_fu_1721_p1;
wire   [17:0] p_shl_fu_1746_p3;
wire   [17:0] zext_ln170_2_fu_1743_p1;
wire   [17:0] zext_ln170_3_fu_1796_p1;
wire   [17:0] mixed_fu_1799_p2;
wire   [13:0] or_ln2_fu_1820_p4;
wire   [17:0] zext_ln170_4_fu_1828_p1;
wire   [17:0] mixed_1_fu_1832_p2;
wire   [10:0] grp_fu_1875_p0;
wire   [6:0] grp_fu_1875_p1;
wire   [9:0] grp_fu_1875_p2;
wire    ap_CS_fsm_state13;
reg   [32:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire   [27:0] grp_fu_1147_p00;
wire   [29:0] grp_fu_1156_p00;
wire   [16:0] grp_fu_1875_p00;
wire   [31:0] grp_fu_763_p00;
wire   [31:0] grp_fu_763_p10;
wire  signed [2:0] target_gain_q8_fu_1685_p1;
wire   [2:0] target_gain_q8_fu_1685_p3;
wire   [2:0] target_gain_q8_fu_1685_p5;
wire   [2:0] target_gain_q8_fu_1685_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 bram_addr_reg = 19'd0;
#0 line_num_addr_reg = 8'd0;
#0 video_started = 1'd0;
#0 state = 3'd0;
#0 out_line = 12'd0;
#0 packet_idx = 4'd0;
#0 line_pixel_idx = 12'd0;
#0 payload_word = 65'd0;
#0 adaptive_black = 16'd0;
#0 adaptive_gain_q8 = 16'd256;
#0 frame_min = 16'd65535;
#0 frame_max = 16'd0;
#0 out_slot = 8'd0;
#0 packet_pixel_idx = 7'd0;
#0 pack_idx = 2'd0;
#0 payload_last = 1'd0;
#0 source_pixel_reg = 16'd0;
#0 adaptive_valid = 1'd0;
#0 ap_CS_fsm = 33'd1;
end

fisheye_remap_reader_hls_kLaserScaleQ16_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 101 ),
    .AddressWidth( 7 ))
kLaserScaleQ16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kLaserScaleQ16_address0),
    .ce0(kLaserScaleQ16_ce0_local),
    .q0(kLaserScaleQ16_q0)
);

fisheye_remap_reader_hls_kInfraredScaleQ16_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 101 ),
    .AddressWidth( 7 ))
kInfraredScaleQ16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kInfraredScaleQ16_address0),
    .ce0(kInfraredScaleQ16_ce0_local),
    .q0(kInfraredScaleQ16_q0)
);

fisheye_remap_reader_hls_mul_16ns_16ns_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16ns_16ns_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_763_p0),
    .din1(grp_fu_763_p1),
    .ce(1'b1),
    .dout(grp_fu_763_p2)
);

fisheye_remap_reader_hls_mul_17ns_11s_28_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 28 ))
mul_17ns_11s_28_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1147_p0),
    .din1(dx_reg_2058),
    .ce(1'b1),
    .dout(grp_fu_1147_p2)
);

fisheye_remap_reader_hls_mul_17ns_13s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 30 ))
mul_17ns_13s_30_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1156_p0),
    .din1(dy_reg_2003),
    .ce(1'b1),
    .dout(grp_fu_1156_p2)
);

(* dissolve_hierarchy = "yes" *) fisheye_remap_reader_hls_sparsemux_9_3_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 14 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 14 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 14 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 14 ),
    .def_WIDTH( 14 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 14 ))
sparsemux_9_3_14_1_1_U4(
    .din0(14'd512),
    .din1(14'd1024),
    .din2(14'd2048),
    .din3(target_gain_q8_fu_1685_p8),
    .def(target_gain_q8_fu_1685_p9),
    .sel(target_gain_q8_fu_1685_p10),
    .dout(target_gain_q8_fu_1685_p11)
);

fisheye_remap_reader_hls_mac_muladd_11ns_7ns_10ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mac_muladd_11ns_7ns_10ns_17_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1875_p0),
    .din1(grp_fu_1875_p1),
    .din2(grp_fu_1875_p2),
    .ce(1'b1),
    .dout(grp_fu_1875_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        adaptive_black <= 16'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state31) & (((1'd0 == adaptive_valid_load_reg_2282) & (trunc_ln367_reg_2278 == 1'd0)) | ((1'd0 == adaptive_valid_load_reg_2282) & (or_ln367_fu_1581_p2 == 1'd1))))) begin
            adaptive_black <= 16'd0;
        end else if (((1'd0 == adaptive_valid_load_reg_2282) & (or_ln367_fu_1581_p2 == 1'd0) & (trunc_ln367_reg_2278 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
            adaptive_black <= new_value_reg_1949;
        end else if (((1'd1 == adaptive_valid_load_reg_2282) & (or_ln367_reg_2296 == 1'd0) & (trunc_ln367_reg_2278 == 1'd1) & (tmp_18_reg_2266 == 1'd0) & (icmp_ln365_reg_2262 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
            adaptive_black <= {{mixed_fu_1799_p2[17:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        adaptive_gain_q8 <= 16'd256;
    end else begin
        if (((1'b1 == ap_CS_fsm_state31) & (((1'd0 == adaptive_valid_load_reg_2282) & (trunc_ln367_reg_2278 == 1'd0)) | ((1'd0 == adaptive_valid_load_reg_2282) & (or_ln367_fu_1581_p2 == 1'd1))))) begin
            adaptive_gain_q8 <= 16'd256;
        end else if (((1'd1 == adaptive_valid_load_reg_2282) & (or_ln367_reg_2296 == 1'd0) & (trunc_ln367_reg_2278 == 1'd1) & (tmp_18_reg_2266 == 1'd0) & (icmp_ln365_reg_2262 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
            adaptive_gain_q8 <= {{mixed_1_fu_1832_p2[17:2]}};
        end else if (((1'd0 == adaptive_valid_load_reg_2282) & (or_ln367_reg_2296 == 1'd0) & (trunc_ln367_reg_2278 == 1'd1) & (tmp_18_reg_2266 == 1'd0) & (icmp_ln365_reg_2262 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
            adaptive_gain_q8 <= zext_ln368_reg_2300;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        adaptive_valid <= 1'd0;
    end else begin
        if (((1'd0 == adaptive_valid_load_reg_2282) & (or_ln367_reg_2296 == 1'd0) & (trunc_ln367_reg_2278 == 1'd1) & (tmp_18_reg_2266 == 1'd0) & (icmp_ln365_reg_2262 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
            adaptive_valid <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        bram_addr_reg <= 19'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state27) & (state_load_reg_1904 == 3'd3))) begin
            bram_addr_reg <= or4_i_fu_1419_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        frame_max <= 16'd0;
    end else begin
        if (((icmp_ln321_fu_553_p2 == 1'd1) & (trunc_ln317_fu_529_p1 == 1'd1) & (tmp_17_fu_533_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd6))) begin
            frame_max <= source_pixel_reg;
        end else if (((tmp_18_reg_2266 == 1'd0) & (icmp_ln365_reg_2262 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
            frame_max <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        frame_min <= 16'd65535;
    end else begin
        if (((icmp_ln318_fu_541_p2 == 1'd1) & (trunc_ln317_fu_529_p1 == 1'd1) & (tmp_17_fu_533_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd6))) begin
            frame_min <= source_pixel_reg;
        end else if (((tmp_18_reg_2266 == 1'd0) & (icmp_ln365_reg_2262 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
            frame_min <= 16'd65535;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        line_num_addr_reg <= 8'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (or_ln263_fu_725_p2 == 1'd1) & (state_load_load_fu_471_p1 == 3'd0) & (bram_line_cur_w_en_read_read_fu_346_p2 == 1'd1))) begin
            line_num_addr_reg <= add_ln27_fu_739_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        line_pixel_idx <= 12'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1))) begin
            line_pixel_idx <= 12'd0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            line_pixel_idx <= add_ln342_fu_891_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        out_line <= 12'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1))) begin
            out_line <= bram_line_num;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        out_slot <= 8'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (or_ln263_fu_725_p2 == 1'd1) & (state_load_load_fu_471_p1 == 3'd0) & (bram_line_cur_w_en_read_read_fu_346_p2 == 1'd1))) begin
            out_slot <= add_ln27_fu_739_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pack_idx <= 2'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            pack_idx <= add_ln349_fu_920_p2;
        end else if ((((1'b1 == ap_CS_fsm_state28) & (fifo_almost_full_read_reg_1893 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1)))) begin
            pack_idx <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        packet_idx <= 4'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1))) begin
            packet_idx <= 4'd0;
        end else if (((icmp_ln363_fu_1519_p2 == 1'd0) & (payload_last_load_load_fu_1491_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
            packet_idx <= add_ln386_fu_1524_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        packet_pixel_idx <= 7'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            packet_pixel_idx <= add_ln343_fu_902_p2;
        end else if ((((payload_last_load_load_fu_1491_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state30)) | ((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1)))) begin
            packet_pixel_idx <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        payload_last <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1))) begin
            payload_last <= 1'd0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            payload_last <= icmp_ln340_fu_879_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        payload_word <= 65'd0;
    end else begin
        if (((pack_idx_load_load_fu_801_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state6))) begin
            payload_word <= tmp_1_fu_860_p4;
        end else if (((pack_idx_load_load_fu_801_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state6))) begin
            payload_word <= tmp_5_fu_845_p4;
        end else if (((pack_idx_load_load_fu_801_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state6))) begin
            payload_word <= tmp_10_fu_830_p4;
        end else if (((pack_idx_load_load_fu_801_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state6))) begin
            payload_word <= tmp_11_fu_815_p4;
        end else if (((1'b1 == ap_CS_fsm_state30) | ((1'b1 == ap_CS_fsm_state28) & (fifo_almost_full_read_reg_1893 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1)))) begin
            payload_word <= 65'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        source_pixel_reg <= 16'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd5))) begin
            source_pixel_reg <= bram_doutb;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        state <= 3'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd1))) begin
            state <= 3'd2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd4))) begin
            state <= 3'd5;
        end else if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd5))) begin
            state <= 3'd6;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            state <= select_ln345_fu_926_p3;
        end else if (((1'b1 == ap_CS_fsm_state27) & (state_load_reg_1904 == 3'd3))) begin
            state <= 3'd4;
        end else if (((1'b1 == ap_CS_fsm_state28) & (fifo_almost_full_read_reg_1893 == 1'd0))) begin
            state <= 3'd3;
        end else if (((1'b1 == ap_CS_fsm_state29) & (or_ln263_reg_2020 == 1'd1) & (bram_line_cur_w_en_read_reg_1897 == 1'd1))) begin
            state <= 3'd1;
        end else if (((1'b1 == ap_CS_fsm_state33) & (fifo_almost_full_read_reg_1893 == 1'd0))) begin
            state <= storemerge958_0_0_027_cast_fu_1865_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_started <= 1'd0;
    end else begin
        if (((icmp_ln257_fu_459_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (bram_line_cur_w_en_read_read_fu_346_p2 == 1'd1))) begin
            video_started <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_pixel_1_reg_415 <= output_pixel_3_reg_2044;
    end else if (((1'b1 == ap_CS_fsm_state1) & (((trunc_ln317_fu_529_p1 == 1'd0) & (state_load_load_fu_471_p1 == 3'd6)) | ((tmp_17_fu_533_p3 == 1'd1) & (state_load_load_fu_471_p1 == 3'd6))))) begin
        output_pixel_1_reg_415 <= source_pixel_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        storemerge958_0_0_027_reg_424 <= 2'd0;
    end else if (((payload_last_load_load_fu_1491_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        storemerge958_0_0_027_reg_424 <= 2'd3;
    end else if (((icmp_ln363_fu_1519_p2 == 1'd0) & (payload_last_load_load_fu_1491_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
        storemerge958_0_0_027_reg_424 <= 2'd2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        adaptive_black_1_reg_1936 <= adaptive_black;
        adaptive_gain_q8_1_reg_1942 <= adaptive_gain_q8;
        algo_ctrl_read_reg_1884 <= algo_ctrl;
        bit_sel_reg_1988 <= line_pixel_idx[32'd10];
        bram_line_cur_w_en_read_reg_1897 <= bram_line_cur_w_en;
        delta_reg_2013 <= delta_fu_655_p3;
        dy_reg_2003 <= dy_fu_629_p2;
        fifo_almost_full_read_reg_1893 <= fifo_almost_full;
        frame_max_load_reg_1956 <= frame_max;
        line_pixel_idx_load_reg_1920 <= line_pixel_idx;
        new_value_reg_1949 <= frame_min;
        or_ln263_reg_2020 <= or_ln263_fu_725_p2;
        out_x_reg_1983 <= out_x_fu_603_p1;
        out_y_reg_1908 <= out_line;
        packet_idx_load_reg_1914 <= packet_idx;
        payload_word_load_reg_1927 <= payload_word;
        shifted_1_reg_1978 <= shifted_1_fu_577_p3;
        state_load_reg_1904 <= state;
        sub_ln34_reg_2008 <= sub_ln34_fu_635_p2;
        xor_ln125_reg_1993 <= xor_ln125_fu_619_p2;
        zext_ln126_reg_1998[11 : 0] <= zext_ln126_fu_625_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        adaptive_valid_load_reg_2282 <= adaptive_valid;
        frame_span_reg_2270 <= frame_span_fu_1547_p2;
        icmp_ln365_reg_2262 <= icmp_ln365_fu_1535_p2;
        icmp_ln367_reg_2291 <= icmp_ln367_fu_1575_p2;
        tmp_18_reg_2266 <= algo_ctrl_read_reg_1884[32'd5];
        tmp_20_reg_2286 <= algo_ctrl_read_reg_1884[32'd4];
        trunc_ln367_reg_2278 <= trunc_ln367_fu_1551_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        add_ln170_reg_2310 <= add_ln170_fu_1737_p2;
        or_ln367_reg_2296 <= or_ln367_fu_1581_p2;
        sub_ln170_1_reg_2315 <= sub_ln170_1_fu_1753_p2;
        sub_ln170_reg_2305 <= sub_ln170_fu_1731_p2;
        tmp_13_reg_2320 <= {{target_gain_q8_fu_1685_p11[13:2]}};
        trunc_ln170_reg_2325 <= trunc_ln170_fu_1769_p1;
        zext_ln368_reg_2300[13 : 0] <= zext_ln368_fu_1709_p1[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        delta_line_reg_2203 <= delta_line_fu_1313_p2;
        src_x_1_reg_2208 <= src_x_1_fu_1318_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        dx_reg_2058 <= dx_fu_952_p3;
        icmp_ln61_reg_2069 <= icmp_ln61_fu_973_p2;
        sext_ln32_reg_2063 <= sext_ln32_fu_969_p1;
        tmp_2_reg_2075 <= algo_ctrl_read_reg_1884[32'd3];
        trunc_ln119_reg_2052 <= trunc_ln119_fu_946_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        icmp_ln42_reg_2198 <= icmp_ln42_fu_1234_p2;
        icmp_ln53_reg_2193 <= icmp_ln53_fu_1218_p2;
        src_x_s_reg_2176 <= src_x_s_fu_1185_p2;
        src_y_s_reg_2182 <= src_y_s_fu_1194_p2;
        tmp_8_reg_2187 <= src_y_s_fu_1194_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        kInfraredScaleQ16_load_reg_2125 <= kInfraredScaleQ16_q0;
        kLaserScaleQ16_load_reg_2120 <= kLaserScaleQ16_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        lut_idx_reg_2105 <= {{grp_fu_1875_p3[16:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        output_pixel_3_reg_2044 <= output_pixel_3_fu_794_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        output_pixel_reg_2039 <= {{grp_fu_763_p2[23:8]}};
        tmp_19_reg_2034 <= {{grp_fu_763_p2[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        radius_1_reg_2090 <= radius_1_fu_1036_p1;
        radius_reg_2085 <= radius_fu_1030_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        radius_2_reg_2095 <= radius_2_fu_1045_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        scale_q16_1_reg_2130 <= scale_q16_1_fu_1069_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        slot_2_reg_2227 <= slot_2_fu_1350_p3;
        tmp_16_reg_2233 <= slot_2_fu_1350_p3[32'd12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        slot_4_reg_2238 <= slot_4_fu_1369_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        slot_6_reg_2245 <= slot_6_fu_1385_p3;
        trunc_ln107_reg_2250 <= trunc_ln107_fu_1392_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        slot_reg_2216 <= slot_fu_1332_p2;
        tmp_15_reg_2222 <= slot_fu_1332_p2[32'd12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sub_ln63_reg_2080 <= sub_ln63_fu_1002_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_6_reg_2166 <= {{grp_fu_1147_p2[27:16]}};
        tmp_7_reg_2171 <= {{grp_fu_1156_p2[29:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        trunc_ln_reg_2136 <= {{sub_ln84_fu_1096_p2[23:8]}};
        xor_ln91_reg_2141 <= xor_ln91_fu_1124_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln257_fu_459_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (bram_line_cur_w_en_read_read_fu_346_p2 == 1'd1))) begin
        ap_sig_allocacmp_video_started_load = 1'd1;
    end else begin
        ap_sig_allocacmp_video_started_load = video_started;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        fifo_din = or_ln_fu_1498_p3;
    end else if (((1'b1 == ap_CS_fsm_state28) & (fifo_almost_full_read_reg_1893 == 1'd0))) begin
        fifo_din = zext_ln284_1_fu_1462_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        fifo_din = 65'd0;
    end else begin
        // 新代码：Egor Izmaylov 空闲周期固定为 0，避免 X 污染 FIFO。
        // 旧代码保留：fifo_din = 'bx;
        fifo_din = 65'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | ((1'b1 == ap_CS_fsm_state28) & (fifo_almost_full_read_reg_1893 == 1'd0)))) begin
        fifo_wr_en = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        fifo_wr_en = 1'd0;
    end else begin
        // 新代码：Egor Izmaylov 非写周期固定 wr_en=0。
        // 旧代码保留：fifo_wr_en = 'bx;
        fifo_wr_en = 1'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        kInfraredScaleQ16_ce0_local = 1'b1;
    end else begin
        kInfraredScaleQ16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        kLaserScaleQ16_ce0_local = 1'b1;
    end else begin
        kLaserScaleQ16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd7) & (fifo_almost_full_read_read_fu_328_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd7) & (fifo_almost_full_read_read_fu_328_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else if (((1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd2))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if (((1'b1 == ap_CS_fsm_state1) & ((state_load_load_fu_471_p1 == 3'd1) | ((state_load_load_fu_471_p1 == 3'd5) | (state_load_load_fu_471_p1 == 3'd4))))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else if (((1'b1 == ap_CS_fsm_state1) & (((trunc_ln317_fu_529_p1 == 1'd0) & (state_load_load_fu_471_p1 == 3'd6)) | ((tmp_17_fu_533_p3 == 1'd1) & (state_load_load_fu_471_p1 == 3'd6))))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((trunc_ln317_fu_529_p1 == 1'd1) & (tmp_17_fu_533_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (state_load_load_fu_471_p1 == 3'd6))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state30 : begin
            if (((icmp_ln363_fu_1519_p2 == 1'd1) & (payload_last_load_load_fu_1491_p1 == 1'd1) & (tmp_18_fu_1540_p3 == 1'd0) & (icmp_ln365_fu_1535_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else if (((1'b1 == ap_CS_fsm_state30) & (((icmp_ln363_fu_1519_p2 == 1'd1) & (payload_last_load_load_fu_1491_p1 == 1'd1) & (icmp_ln365_fu_1535_p2 == 1'd0)) | ((icmp_ln363_fu_1519_p2 == 1'd1) & (payload_last_load_load_fu_1491_p1 == 1'd1) & (tmp_18_fu_1540_p3 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln106_fu_1401_p2 = (trunc_ln107_reg_2250 + 8'd56);

assign add_ln170_fu_1737_p2 = (zext_ln170_1_fu_1721_p1 + 17'd2);

assign add_ln27_fu_739_p2 = (select_ln27_fu_731_p3 + cur_slot_fu_715_p1);

assign add_ln342_fu_891_p2 = (line_pixel_idx_load_reg_1920 + 12'd1);

assign add_ln343_fu_902_p2 = (packet_pixel_idx + 7'd1);

assign add_ln349_fu_920_p2 = (pack_idx + 2'd1);

assign add_ln386_fu_1524_p2 = (packet_idx_load_reg_1914 + 4'd1);

assign amplified_scale_q16_fu_1130_p3 = {{xor_ln91_reg_2141}, {trunc_ln_reg_2136}};

assign and_ln156_fu_1651_p2 = (xor_ln153_fu_1645_p2 & icmp_ln156_fu_1601_p2);

assign and_ln159_fu_1669_p2 = (xor_ln156_fu_1663_p2 & icmp_ln159_fu_1616_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bit_sel1_fu_1116_p3 = sext_ln91_fu_1112_p1[17'd16];

assign bit_sel_fu_611_p3 = line_pixel_idx[32'd10];

assign bram_addrb = bram_addr_reg;

assign bram_line_cur_w_en_read_read_fu_346_p2 = bram_line_cur_w_en;

assign bram_line_num_addr = line_num_addr_reg;

assign cur_slot_fu_715_p1 = bram_line_cur_w[7:0];

assign delta_fu_655_p3 = ((tmp_fu_641_p3[0:0] == 1'b1) ? sub_ln34_1_fu_649_p2 : dy_fu_629_p2);

assign delta_line_fu_1313_p2 = (zext_ln140_fu_1309_p1 - zext_ln126_reg_1998);

assign dx_fu_952_p3 = {{xor_ln125_reg_1993}, {trunc_ln125_fu_949_p1}};

assign dy_fu_629_p2 = ($signed(zext_ln126_fu_625_p1) + $signed(13'd7168));

assign fifo_almost_full_read_read_fu_328_p2 = fifo_almost_full;

assign frame_span_fu_1547_p2 = (frame_max_load_reg_1956 - new_value_reg_1949);

assign grp_fu_1147_p0 = grp_fu_1147_p00;

assign grp_fu_1147_p00 = amplified_scale_q16_fu_1130_p3;

assign grp_fu_1156_p0 = grp_fu_1156_p00;

assign grp_fu_1156_p00 = amplified_scale_q16_fu_1130_p3;

assign grp_fu_1875_p0 = grp_fu_1875_p00;

assign grp_fu_1875_p00 = radius_2_reg_2095;

assign grp_fu_1875_p1 = 17'd100;

assign grp_fu_1875_p2 = 17'd512;

assign grp_fu_763_p0 = grp_fu_763_p00;

assign grp_fu_763_p00 = shifted_1_reg_1978;

assign grp_fu_763_p1 = grp_fu_763_p10;

assign grp_fu_763_p10 = adaptive_gain_q8_1_reg_1942;

assign icmp_ln103_fu_1375_p2 = (($signed(slot_4_reg_2238) > $signed(13'd199)) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_1396_p2 = (($signed(slot_6_reg_2245) > $signed(13'd199)) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_789_p2 = ((tmp_19_reg_2034 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln156_fu_1601_p2 = ((tmp_23_fu_1592_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln159_fu_1616_p2 = ((tmp_24_fu_1607_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_1631_p2 = ((tmp_25_fu_1622_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln184_fu_565_p2 = ((source_pixel_reg > adaptive_black) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_459_p2 = ((trunc_ln257_fu_455_p1 > 8'd99) ? 1'b1 : 1'b0);

assign icmp_ln263_fu_719_p2 = ((cur_slot_fu_715_p1 > 8'd99) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_541_p2 = ((source_pixel_reg < frame_min) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_553_p2 = ((source_pixel_reg > frame_max) ? 1'b1 : 1'b0);

assign icmp_ln340_fu_879_p2 = ((packet_pixel_idx == 7'd127) ? 1'b1 : 1'b0);

assign icmp_ln345_fu_914_p2 = ((pack_idx == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln363_fu_1519_p2 = ((line_pixel_idx_load_reg_1920 == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln365_fu_1535_p2 = ((out_y_reg_1908 == 12'd2047) ? 1'b1 : 1'b0);

assign icmp_ln367_fu_1575_p2 = ((tmp_21_fu_1565_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_1234_p2 = (($signed(tmp_14_fu_1224_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_1218_p2 = (($signed(tmp_9_fu_1208_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_973_p2 = ((sext_ln32_fu_969_p1 > delta_reg_2013) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_1040_p2 = ((radius_reg_2085 > 14'd1024) ? 1'b1 : 1'b0);

assign kInfraredScaleQ16_address0 = zext_ln129_fu_1064_p1;

assign kLaserScaleQ16_address0 = zext_ln129_fu_1064_p1;

assign max_v_fu_1008_p3 = ((icmp_ln61_reg_2069[0:0] == 1'b1) ? sext_ln32_reg_2063 : delta_reg_2013);

assign min_v_fu_985_p3 = ((icmp_ln61_reg_2069[0:0] == 1'b1) ? delta_reg_2013 : sext_ln32_reg_2063);

assign mixed_1_fu_1832_p2 = (sub_ln170_1_reg_2315 + zext_ln170_4_fu_1828_p1);

assign mixed_fu_1799_p2 = (zext_ln170_3_fu_1796_p1 + sub_ln170_reg_2305);

assign or4_i_fu_1419_p3 = {{src_slot_1_fu_1413_p3}, {src_x_1_reg_2208}};

assign or_ln156_fu_1657_p2 = (tmp_22_fu_1585_p3 | icmp_ln156_fu_1601_p2);

assign or_ln1_fu_1450_p3 = {{9'd257}, {zext_ln284_fu_1446_p1}};

assign or_ln263_fu_725_p2 = (icmp_ln263_fu_719_p2 | ap_sig_allocacmp_video_started_load);

assign or_ln2_fu_1820_p4 = {{{tmp_13_reg_2320}, {1'd1}}, {trunc_ln170_reg_2325}};

assign or_ln367_fu_1581_p2 = (tmp_20_reg_2286 | icmp_ln367_reg_2291);

assign or_ln39_fu_1296_p2 = (tmp_12_fu_1271_p3 | icmp_ln42_reg_2198);

assign or_ln50_fu_1259_p2 = (tmp_8_reg_2187 | icmp_ln53_reg_2193);

assign or_ln_fu_1498_p3 = {{payload_last}, {trunc_ln357_fu_1495_p1}};

assign out_x_fu_603_p1 = line_pixel_idx[10:0];

assign output_pixel_3_fu_794_p3 = ((icmp_ln145_fu_789_p2[0:0] == 1'b1) ? 16'd65535 : output_pixel_reg_2039);

assign p_shl1_fu_994_p3 = {{min_v_fu_985_p3}, {2'd0}};

assign p_shl2_fu_1724_p3 = {{adaptive_black_1_reg_1936}, {2'd0}};

assign p_shl_fu_1746_p3 = {{adaptive_gain_q8_1_reg_1942}, {2'd0}};

assign pack_idx_load_load_fu_801_p1 = pack_idx;

assign payload_last_load_load_fu_1491_p1 = payload_last;

assign radius_1_fu_1036_p1 = radius_fu_1030_p2[10:0];

assign radius_2_fu_1045_p3 = ((icmp_ln64_fu_1040_p2[0:0] == 1'b1) ? 11'd1024 : radius_1_reg_2090);

assign radius_fu_1030_p2 = (zext_ln63_2_fu_1026_p1 + zext_ln63_fu_1013_p1);

assign scale_q16_1_fu_1069_p3 = ((tmp_2_reg_2075[0:0] == 1'b1) ? kLaserScaleQ16_load_reg_2120 : kInfraredScaleQ16_load_reg_2125);

assign select_ln27_fu_731_p3 = ((icmp_ln263_fu_719_p2[0:0] == 1'b1) ? 8'd156 : 8'd100);

assign select_ln345_fu_926_p3 = ((icmp_ln345_fu_914_p2[0:0] == 1'b1) ? 3'd7 : 3'd3);

assign select_ln34_fu_963_p3 = ((bit_sel_reg_1988[0:0] == 1'b1) ? sext_ln125_fu_959_p1 : sub_ln34_reg_2008);

assign select_ln39_fu_1288_p3 = ((xor_ln39_fu_1282_p2[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign select_ln50_fu_1251_p3 = ((xor_ln50_fu_1246_p2[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign sext_ln125_fu_959_p1 = dx_fu_952_p3;

assign sext_ln136_1_fu_1240_p1 = src_x_s_reg_2176;

assign sext_ln136_fu_1182_p1 = $signed(tmp_6_reg_2166);

assign sext_ln284_fu_1458_p1 = $signed(or_ln1_fu_1450_p3);

assign sext_ln32_fu_969_p1 = $signed(select_ln34_fu_963_p3);

assign sext_ln77_fu_1191_p1 = $signed(tmp_7_reg_2171);

assign sext_ln84_1_fu_1092_p1 = $signed(tmp_4_fu_1085_p3);

assign sext_ln84_fu_1081_p1 = $signed(tmp_3_fu_1074_p3);

assign sext_ln91_fu_1112_p1 = trunc_ln_fu_1102_p4;

assign shifted_1_fu_577_p3 = ((icmp_ln184_fu_565_p2[0:0] == 1'b1) ? shifted_fu_571_p2 : 16'd0);

assign shifted_fu_571_p2 = (source_pixel_reg - adaptive_black);

assign slot_1_fu_1345_p2 = (slot_reg_2216 + 13'd200);

assign slot_2_fu_1350_p3 = ((tmp_15_reg_2222[0:0] == 1'b1) ? slot_1_fu_1345_p2 : slot_reg_2216);

assign slot_3_fu_1364_p2 = (slot_2_reg_2227 + 13'd200);

assign slot_4_fu_1369_p3 = ((tmp_16_reg_2233[0:0] == 1'b1) ? slot_3_fu_1364_p2 : slot_2_reg_2227);

assign slot_5_fu_1380_p2 = ($signed(slot_4_reg_2238) + $signed(13'd7992));

assign slot_6_fu_1385_p3 = ((icmp_ln103_fu_1375_p2[0:0] == 1'b1) ? slot_5_fu_1380_p2 : slot_4_reg_2238);

assign slot_fu_1332_p2 = (delta_line_reg_2203 + zext_ln96_fu_1328_p1);

assign src_slot_1_fu_1413_p3 = ((trunc_ln119_reg_2052[0:0] == 1'b1) ? src_slot_fu_1406_p3 : out_slot);

assign src_slot_fu_1406_p3 = ((icmp_ln106_fu_1396_p2[0:0] == 1'b1) ? add_ln106_fu_1401_p2 : trunc_ln107_reg_2250);

assign src_x_1_fu_1318_p3 = ((trunc_ln119_reg_2052[0:0] == 1'b1) ? src_x_fu_1301_p3 : out_x_reg_1983);

assign src_x_fu_1301_p3 = ((or_ln39_fu_1296_p2[0:0] == 1'b1) ? select_ln39_fu_1288_p3 : trunc_ln45_fu_1279_p1);

assign src_x_s_fu_1185_p2 = ($signed(sext_ln136_fu_1182_p1) + $signed(14'd1024));

assign src_y_fu_1263_p3 = ((or_ln50_fu_1259_p2[0:0] == 1'b1) ? select_ln50_fu_1251_p3 : trunc_ln56_fu_1243_p1);

assign src_y_s_fu_1194_p2 = ($signed(sext_ln77_fu_1191_p1) + $signed(16'd1024));

assign srio_addr_fu_1438_p4 = {{{out_y_reg_1908}, {packet_idx_load_reg_1914}}, {8'd0}};

assign state_load_load_fu_471_p1 = state;

assign storemerge958_0_0_027_cast_fu_1865_p1 = storemerge958_0_0_027_reg_424;

assign sub_ln170_1_fu_1753_p2 = (p_shl_fu_1746_p3 - zext_ln170_2_fu_1743_p1);

assign sub_ln170_fu_1731_p2 = (p_shl2_fu_1724_p3 - zext_ln170_fu_1718_p1);

assign sub_ln34_1_fu_649_p2 = (13'd1024 - zext_ln126_fu_625_p1);

assign sub_ln34_fu_635_p2 = (12'd1024 - zext_ln125_fu_607_p1);

assign sub_ln63_fu_1002_p2 = (p_shl1_fu_994_p3 - zext_ln63_1_fu_990_p1);

assign sub_ln84_fu_1096_p2 = ($signed(sext_ln84_fu_1081_p1) - $signed(sext_ln84_1_fu_1092_p1));

assign target_gain_q8_fu_1685_p10 = {{{tmp_22_fu_1585_p3}, {and_ln156_fu_1651_p2}}, {and_ln159_fu_1669_p2}};

assign target_gain_q8_fu_1685_p8 = ((icmp_ln162_fu_1631_p2[0:0] == 1'b1) ? 14'd4096 : 14'd8192);

assign target_gain_q8_fu_1685_p9 = 'bx;

assign tmp_10_fu_830_p4 = {{payload_word_load_reg_1927[64:32]}, {output_pixel_1_reg_415}, {payload_word_load_reg_1927[15:0]}};

assign tmp_11_fu_815_p4 = {{payload_word_load_reg_1927[64:48]}, {output_pixel_1_reg_415}, {payload_word_load_reg_1927[31:0]}};

assign tmp_12_fu_1271_p3 = sext_ln136_1_fu_1240_p1[32'd15];

assign tmp_14_fu_1224_p4 = {{src_x_s_fu_1185_p2[13:11]}};

assign tmp_17_fu_533_p3 = algo_ctrl[32'd4];

assign tmp_18_fu_1540_p3 = algo_ctrl_read_reg_1884[32'd5];

assign tmp_1_fu_860_p4 = {{payload_word_load_reg_1927[64:64]}, {output_pixel_1_reg_415}, {payload_word_load_reg_1927[47:0]}};

assign tmp_21_fu_1565_p4 = {{frame_span_fu_1547_p2[15:10]}};

assign tmp_22_fu_1585_p3 = frame_span_reg_2270[32'd15];

assign tmp_23_fu_1592_p4 = {{frame_span_reg_2270[15:14]}};

assign tmp_24_fu_1607_p4 = {{frame_span_reg_2270[15:13]}};

assign tmp_25_fu_1622_p4 = {{frame_span_reg_2270[15:12]}};

assign tmp_3_fu_1074_p3 = {{scale_q16_1_reg_2130}, {10'd0}};

assign tmp_4_fu_1085_p3 = {{scale_q16_1_reg_2130}, {8'd0}};

assign tmp_5_fu_845_p4 = {{payload_word_load_reg_1927[64:16]}, {output_pixel_1_reg_415}};

assign tmp_9_fu_1208_p4 = {{src_y_s_fu_1194_p2[15:11]}};

assign tmp_fu_641_p3 = dy_fu_629_p2[32'd12];

assign tmp_s_fu_1017_p4 = {{sub_ln63_reg_2080[14:3]}};

assign trunc_ln107_fu_1392_p1 = slot_6_fu_1385_p3[7:0];

assign trunc_ln119_fu_946_p1 = algo_ctrl_read_reg_1884[0:0];

assign trunc_ln125_fu_949_p1 = line_pixel_idx_load_reg_1920[9:0];

assign trunc_ln170_fu_1769_p1 = target_gain_q8_fu_1685_p11[0:0];

assign trunc_ln257_fu_455_p1 = bram_line_cur_w[7:0];

assign trunc_ln317_fu_529_p1 = algo_ctrl[0:0];

assign trunc_ln357_fu_1495_p1 = payload_word_load_reg_1927[63:0];

assign trunc_ln367_fu_1551_p1 = algo_ctrl_read_reg_1884[0:0];

assign trunc_ln45_fu_1279_p1 = src_x_s_reg_2176[10:0];

assign trunc_ln56_fu_1243_p1 = src_y_s_reg_2182[10:0];

assign trunc_ln_fu_1102_p4 = {{sub_ln84_fu_1096_p2[23:8]}};

assign xor_ln125_fu_619_p2 = (bit_sel_fu_611_p3 ^ 1'd1);

assign xor_ln153_fu_1645_p2 = (tmp_22_fu_1585_p3 ^ 1'd1);

assign xor_ln156_fu_1663_p2 = (or_ln156_fu_1657_p2 ^ 1'd1);

assign xor_ln39_fu_1282_p2 = (tmp_12_fu_1271_p3 ^ 1'd1);

assign xor_ln50_fu_1246_p2 = (tmp_8_reg_2187 ^ 1'd1);

assign xor_ln91_fu_1124_p2 = (bit_sel1_fu_1116_p3 ^ 1'd1);

assign zext_ln125_fu_607_p1 = out_x_fu_603_p1;

assign zext_ln126_fu_625_p1 = out_line;

assign zext_ln129_fu_1064_p1 = lut_idx_reg_2105;

assign zext_ln140_fu_1309_p1 = src_y_fu_1263_p3;

assign zext_ln170_1_fu_1721_p1 = new_value_reg_1949;

assign zext_ln170_2_fu_1743_p1 = adaptive_gain_q8_1_reg_1942;

assign zext_ln170_3_fu_1796_p1 = add_ln170_reg_2310;

assign zext_ln170_4_fu_1828_p1 = or_ln2_fu_1820_p4;

assign zext_ln170_fu_1718_p1 = adaptive_black_1_reg_1936;

assign zext_ln284_1_fu_1462_p1 = $unsigned(sext_ln284_fu_1458_p1);

assign zext_ln284_fu_1446_p1 = srio_addr_fu_1438_p4;

assign zext_ln368_fu_1709_p1 = target_gain_q8_fu_1685_p11;

assign zext_ln63_1_fu_990_p1 = min_v_fu_985_p3;

assign zext_ln63_2_fu_1026_p1 = tmp_s_fu_1017_p4;

assign zext_ln63_fu_1013_p1 = max_v_fu_1008_p3;

assign zext_ln96_fu_1328_p1 = out_slot;

always @ (posedge ap_clk) begin
    zext_ln126_reg_1998[12] <= 1'b0;
    zext_ln368_reg_2300[15:14] <= 2'b00;
end

endmodule //fisheye_remap_reader_hls
